Imports System.IO
Imports System.Threading.Tasks
Imports FO4_Base_Library

''' <summary>El preflight de NPC Manager: el formulario COMPARTIDO de la libreria (<see cref="LoadOrderPreflight_Form"/>)
''' con lo propio de esta app — la seleccion guardada por juego en npc_config.json, los gates que dependen del juego
''' fijado, el plugin de F4SE, y los dos escaneos posteriores a la carga (plugins autogenerados y sidecars
''' .bssliders). Program.vb, MainForm y BakeAllRunner lo usan con el mismo nombre de siempre.</summary>
Public Class Preflight_Form
    Inherits LoadOrderPreflight_Form

    ''' <summary>NPC_Manager auto-generated plugins detected on disk during preflight. MainForm
    ''' uses this as the seed for its Save-ESP cache so the first Save dialog opens without a
    ''' visible disk scan. Null until OK + load completes.</summary>
    Public Property LoadedAutoGenPlugins As List(Of SaveEsp_Form.ExistingPlugin)

    ''' <summary>Per-plugin <c>.bssliders</c> sidecars discovered next to the user-selected
    ''' plugins. Key = plugin filename (e.g. <c>"NPC_Manager.esp"</c>, case-insensitive); value
    ''' = parsed sidecar. Plugins without a sidecar on disk are absent from the dict.</summary>
    Public Property LoadedSidecars As Dictionary(Of String, BssliderSidecar.SidecarFile)

    Public Sub New()
        ' La version, TAMBIEN aca: esta es la PRIMERA ventana que ve el usuario de NPC Manager.
        WindowTitle = VersionGate.TituloConVersion("FO4 NPC Manager") & " — Setup"
    End Sub

    Protected Overrides Function LoadSavedSelection(game As Config_App.Game_Enum) As IEnumerable(Of String)
        Return NPC_Config.GetPreflightSelection(game)
    End Function

    Protected Overrides Sub SaveSelection(game As Config_App.Game_Enum, literalOrNothing As List(Of String))
        NPC_Config.SetPreflightSelection(game, literalOrNothing)
        NPC_Config.SaveConfig()
    End Sub

    Protected Overrides Sub OnGameCommitted(game As Config_App.Game_Enum)
        ' El juego queda FIJADO aca ⇒ re-aplicar el gate por juego de la ley opt-in del CK (blend de skin NO
        ' normalizado), y los settings de decodificacion.
        NPC_Config.ApplyEngineSkinWeightNormalizationGate(game)
        NPC_Config.ApplyGlDecodeSetting()
        NPC_Config.ApplyDownsizeFromMip0Setting()
        ' Primer momento en que se puede instalar el plugin de F4SE en el Data correcto. No hace nada en Skyrim.
        NativePluginInstaller.Reconcile()
    End Sub

    Protected Overrides Async Function RunPostLoadStepsAsync(pm As PluginManager, dataPath As String,
                                                            selected As IReadOnlyList(Of String),
                                                            setStatus As Action(Of String)) As Task
        ' Plugins autogenerados de NPC_Manager en Data (solo abre el TES4 de cada uno): el primer Save ESP abre al
        ' instante. Ver MainForm._autoGenPluginsCache.
        Dim scanProgress As New Progress(Of String)(Sub(msg) setStatus(msg))
        LoadedAutoGenPlugins = Await Task.Run(
            Function() SaveEsp_Form.ScanAutoGeneratedPlugins(dataPath, pm, scanProgress))

        ' Sidecars <plugin>.bssliders junto a los plugins elegidos, en el worker.
        setStatus("Scanning .bssliders sidecars...")
        Dim sel = selected.ToList()
        LoadedSidecars = Await Task.Run(Function() ScanSidecarsForPlugins(dataPath, sel))
    End Function

    ''' <summary>Iterate the user-selected plugins, check for a sibling <c>.bssliders</c> file,
    ''' and parse the ones that exist. Plugins without a sidecar are simply absent from the
    ''' result dict. Best-effort: a malformed sidecar is skipped silently (its NPCs render with
    ''' no overlay, same as if the user had never edited them). Keyed by plugin filename,
    ''' case-insensitive.</summary>
    ''' <remarks>Friend (not Private) so the headless bake (Program.HeadlessBakeAll) scans sidecars
    ''' through the very same function the preflight uses.</remarks>
    Friend Shared Function ScanSidecarsForPlugins(dataPath As String,
                                                  pluginNames As List(Of String)) As Dictionary(Of String, BssliderSidecar.SidecarFile)
        Dim result As New Dictionary(Of String, BssliderSidecar.SidecarFile)(StringComparer.OrdinalIgnoreCase)
        If String.IsNullOrEmpty(dataPath) OrElse pluginNames Is Nothing Then Return result
        For Each pluginName In pluginNames
            Dim espPath = IO.Path.Combine(dataPath, pluginName)
            Dim sidecarPath = BssliderSidecar.BuildPath(espPath)
            If String.IsNullOrEmpty(sidecarPath) OrElse Not IO.File.Exists(sidecarPath) Then Continue For
            Dim parsed = BssliderSidecar.Read(sidecarPath)
            If parsed IsNot Nothing Then result(pluginName) = parsed
        Next
        Return result
    End Function

End Class
