Imports System.IO
Imports System.Linq
Imports FO4_Base_Library

''' <summary>
''' Dialog for "Save ESP/ESM" — picks a target plugin (existing auto-generated or new)
''' and the light-master flag. Scans the Data\ folder for plugins whose TES4.CNAM matches
''' the NPC_Manager canonical author string and lists them as "update existing" candidates.
''' </summary>
Public Class SaveEsp_Form

    ' ============================================================================
    ' Shared scan helpers (used by both Preflight_Form to populate the cache up-front
    ' during the splash, and by MainForm to re-scan if needed).
    ' ============================================================================

    ''' <summary>Full disk scan for NPC_Manager auto-generated plugins. Walks Data\, filters by
    ''' TES4.CNAM matching <see cref="PluginWriter.NPC_MANAGER_AUTHOR_CNAM"/>, then loads each
    ''' match to enumerate its NPC overrides. Best-effort: malformed plugins are skipped silently.
    '''
    ''' Designed to run during Preflight (splash screen) so the first Save ESP dialog opens
    ''' instantly. Reports progress via the optional <paramref name="progress"/> callback.</summary>
    Public Shared Function ScanAutoGeneratedPlugins(dataPath As String, Optional progress As IProgress(Of String) = Nothing) As List(Of ExistingPlugin)
        Dim result As New List(Of ExistingPlugin)
        If String.IsNullOrEmpty(dataPath) OrElse Not Directory.Exists(dataPath) Then Return result

        Dim pluginFiles = Directory.GetFiles(dataPath, "*.esp").
            Concat(Directory.GetFiles(dataPath, "*.esm")).
            Concat(Directory.GetFiles(dataPath, "*.esl")).
            ToList()

        Dim total = pluginFiles.Count
        Dim idx As Integer = 0
        For Each filePath In pluginFiles
            idx += 1
            Try
                Dim author = TryReadTes4Author(filePath)
                If author Is Nothing OrElse Not String.Equals(author, PluginWriter.NPC_MANAGER_AUTHOR_CNAM, StringComparison.Ordinal) Then
                    Continue For
                End If

                progress?.Report($"Scanning auto-generated plugins ({idx}/{total}): {Path.GetFileName(filePath)}")

                Dim reader As New PluginReader()
                reader.Load(filePath)
                Dim npcIds As New HashSet(Of UInteger)
                ' Compute "originates a new self record" here (same pass) so the UI-thread
                ' risky-ESL-flip check (PluginHasNewSelfRecords) is a cache hit instead of a
                ' synchronous reader.Load. A self record's FormID high byte ≥ master count.
                Dim masterCount = CUInt(reader.Masters.Count)
                Dim hasNewSelf As Boolean = False
                For Each kvp In reader.Records
                    If kvp.Value.Header.Signature = "NPC_" Then npcIds.Add(kvp.Key)
                    If Not hasNewSelf AndAlso (kvp.Key >> 24) >= masterCount Then hasNewSelf = True
                Next
                Dim ep As New ExistingPlugin With {
                    .FullPath = filePath,
                    .FileName = Path.GetFileName(filePath),
                    .NpcCount = npcIds.Count,
                    .NpcFormIDs = npcIds,
                    .ContainsTargetNpc = False,
                    .IsEsm = reader.IsESM,
                    .IsLight = reader.IsESL,
                    .TranslatableEncoding = reader.TranslatableEncoding,
                    .HasNewSelfRecords = hasNewSelf
                }
                result.Add(ep)
            Catch
                ' Plugin failed to read or open — skip silently.
            End Try
        Next
        Return result
    End Function

    ''' <summary>Read just the TES4 CNAM (author string) from a plugin file. Returns Nothing
    ''' if the plugin is malformed or has no author. Cheap: only reads the TES4 record body
    ''' (typically &lt; 1 KB) so the scan can dismiss most plugins without loading them.</summary>
    Public Shared Function TryReadTes4Author(path As String) As String
        Try
            Using fs As New FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read)
                Using br As New BinaryReader(fs)
                    ' TES4 record header layout (24 bytes total):
                    '   +0  sig "TES4" (4)
                    '   +4  DataSize u32 (4)
                    '   +8  Flags u32 (4)
                    '   +12 FormID u32 (4)
                    '   +16 VCS1 u32 (4)
                    '   +20 Version u16 (2)
                    '   +22 VCS2 u16 (2)
                    ' After reading sig+DataSize (8 bytes consumed), skip 16 more to land at body.
                    Dim sig = System.Text.Encoding.ASCII.GetString(br.ReadBytes(4))
                    If sig <> "TES4" Then Return Nothing
                    Dim dataSize = br.ReadUInt32()
                    fs.Seek(16, SeekOrigin.Current)
                    Dim bodyEnd = fs.Position + CLng(dataSize)

                    ' Two-pass to honor per-file SNAM <cp:XXXX> tag (xEdit flEncodingTrans):
                    ' first scan locates CNAM bytes + SNAM tag, then decodes CNAM with the
                    ' per-file encoding when present. xEdit canonical FO4 order is CNAM before
                    ' SNAM, so the on-disk CNAM is reached first while seeking — buffer its
                    ' bytes and resolve later. ASCII-only author literals are encoding-invariant
                    ' so the typical NPC_Manager scan path works either way; this loop is the
                    ' robust path for tooling that ever writes non-ASCII authors.
                    Dim cnamBytes As Byte() = Nothing
                    Dim perFileEnc As System.Text.Encoding = Nothing

                    While fs.Position <= bodyEnd - 6
                        Dim subSig = System.Text.Encoding.ASCII.GetString(br.ReadBytes(4))
                        Dim subSize = br.ReadUInt16()
                        If subSig = "CNAM" Then
                            cnamBytes = br.ReadBytes(CInt(subSize))
                        ElseIf subSig = "SNAM" Then
                            Dim snamBytes = br.ReadBytes(CInt(subSize))
                            Dim snamLen = snamBytes.Length
                            If snamLen > 0 AndAlso snamBytes(snamLen - 1) = 0 Then snamLen -= 1
                            Dim snamText = PluginEncodingSettings.DecodeTranslatable(snamBytes, 0, snamLen)
                            perFileEnc = PluginEncodingSettings.ParseSnamCpTag(snamText)
                            ' CNAM seen first per xEdit canonical order — we have what we need.
                            If cnamBytes IsNot Nothing Then Exit While
                        Else
                            fs.Seek(CLng(subSize), SeekOrigin.Current)
                        End If
                    End While

                    If cnamBytes Is Nothing Then Return Nothing
                    Dim cnamLen = cnamBytes.Length
                    If cnamLen > 0 AndAlso cnamBytes(cnamLen - 1) = 0 Then cnamLen -= 1
                    If perFileEnc IsNot Nothing Then
                        Return PluginEncodingSettings.DecodeWithEncoding(cnamBytes, 0, cnamLen, perFileEnc)
                    End If
                    Return PluginEncodingSettings.DecodeTranslatable(cnamBytes, 0, cnamLen)
                End Using
            End Using
        Catch
            Return Nothing
        End Try
        Return Nothing
    End Function

    ''' <summary>An auto-generated plugin found on disk that the user can update.</summary>
    Public Class ExistingPlugin
        Public FileName As String
        Public FullPath As String
        Public NpcCount As Integer
        ''' <summary>FormIDs of the NPC_ overrides this plugin contains. Captured at scan time
        ''' so the cache can answer ContainsTargetNpc for any target NPC without re-reading
        ''' the plugin from disk.</summary>
        Public NpcFormIDs As HashSet(Of UInteger)
        Public ContainsTargetNpc As Boolean
        ''' <summary>TES4 header flags read at scan time. Used by the dialog to auto-populate
        ''' the Master / Light checkboxes when the user picks "Update existing", so the saved
        ''' plugin keeps the same flag set unless the user explicitly changes them.</summary>
        Public IsEsm As Boolean
        Public IsLight As Boolean
        ''' <summary>Per-file translatable encoding parsed from the plugin's TES4 SNAM
        ''' &lt;cp:XXXX&gt; tag at scan time. Nothing when the plugin has no tag (default →
        ''' global Translatable). Used by the Save dialog to auto-select the encoding combo
        ''' when the user picks "Update existing", so the rewrite keeps the same encoding
        ''' the file originally had unless the user explicitly changes it.</summary>
        Public TranslatableEncoding As System.Text.Encoding
        ''' <summary>Whether the plugin ORIGINATES at least one record (a "self" record whose
        ''' FormID high byte ≥ the plugin's master count) vs. being a pure override plugin.
        ''' Computed during the background Preflight scan (which already loads the plugin), so the
        ''' UI-thread risky-ESL-flip check is a cache hit instead of a synchronous reader.Load.
        ''' Nothing when not pre-computed (e.g. a plugin added to the cache post-save by MainForm),
        ''' in which case PluginHasNewSelfRecords falls back to an on-demand load.</summary>
        Public HasNewSelfRecords As Boolean?

        Public Overrides Function ToString() As String
            Dim suffix As String = ""
            If ContainsTargetNpc Then
                suffix = "  (already contains this NPC — will be replaced)"
            ElseIf NpcCount > 0 Then
                suffix = $"  ({NpcCount} NPC override{If(NpcCount = 1, "", "s")})"
            End If
            Return $"{FileName}{suffix}"
        End Function
    End Class

    ''' <summary>Result of the dialog when the user clicks Save.</summary>
    Public Class SaveTarget
        Public TargetPath As String
        Public IsNewPlugin As Boolean
        ''' <summary>TES4 header ESM flag (0x01). When False the file is written as a plain
        ''' ESP without the master flag. Independent of <see cref="LightMaster"/>.</summary>
        Public MarkAsMaster As Boolean
        Public LightMaster As Boolean
        Public ReplacingExistingNpc As Boolean
        ''' <summary>When True the caller should bake the CharGen NIF + textures and pack
        ''' them into <c>&lt;plugin&gt; - Main.ba2</c> + <c>&lt;plugin&gt; - Textures.ba2</c> after
        ''' writing the override. Default True. Forced True (read-only) when the source NPC
        ''' has no CharGen Face Preset flag — those NPCs the engine bakes via CK and the BA2
        ''' is the only way they render in-world without a CK pass.</summary>
        Public GenerateChargen As Boolean
        ''' <summary>When True (and <see cref="GenerateChargen"/> is also True), the orchestrator clears the
        ''' ACBS "Is CharGen Face Preset" flag (bit 0x04) on every saved NPC override, so the engine loads
        ''' the freshly baked FaceGen instead of reconstructing the face at runtime. Only meaningful when the
        ''' CharGen bake runs; the dialog disables + unchecks the option when the bake is off. Default False.</summary>
        Public RemoveCharGenFlag As Boolean
        ''' <summary>El sidecar <c>&lt;plugin&gt;.bssliders</c> se escribe SIEMPRE. Era un checkbox y se quitó:
        ''' no es una opción de salida, es la BASE DE DATOS de la app, y apagarlo rompía cosas en silencio.
        '''
        ''' <list type="number">
        ''' <item><b>Se perdía el contador de generación.</b> <c>payloadGeneration</c> vive en el sidecar y se
        ''' persistía DENTRO de este gate, así que emitir el apply-script con el sidecar apagado dejaba el
        ''' contador sin avanzar ⇒ el siguiente Save ESP reusaba el mismo <c>_G&lt;n&gt;</c> ⇒ a un jugador que ya
        ''' tuviera esa generación le llegaban las properties RANCIAS. Es exactamente la falla que el esquema
        ''' <c>_G&lt;n&gt;</c> existe para evitar.</item>
        ''' <item><b>El NPC quedaba sin payload reconstruible.</b> Overlays, skin, node transforms y body morphs
        ''' NO están en el record: el sidecar es su único hogar. Sin entrada, ni
        ''' <see cref="BssliderSidecar.HydratePresets"/> los restaura al reabrir el plugin, ni el emisor del .ini
        ''' los lista, ni <c>RefreshPreservedApplyScripts</c> puede re-emitir su VMAD.</item>
        ''' </list>
        '''
        ''' <para>Escribirlo siempre es inocuo: <see cref="BssliderSidecar.Write"/> descarta las entradas vacías y
        ''' no crea un archivo cuando no hay nada que guardar ni generación que recordar.</para></summary>
        Public ReadOnly Property WriteBssliders As Boolean
            Get
                Return True
            End Get
        End Property
        ''' <summary>When True the orchestrator emits the BodyGen .ini pair (<c>templates.ini</c> +
        ''' <c>morphs.ini</c>) so the engine applies the body sliders to NPCs on first-load. Game-aware output
        ''' dir: FO4 → <c>Data\F4SE\Plugins\F4EE\BodyGen\&lt;plugin&gt;\</c> (LooksMenu); SSE →
        ''' <c>Data\Meshes\actors\character\BodyGenData\&lt;plugin&gt;\</c> (RaceMenu).
        '''
        ''' <para>⭐ INDEPENDIENTE de <see cref="EmitApplyScript"/>, y las cuatro combinaciones son válidas: el
        ''' script GANA por construcción corra antes o después que BodyGen (si va primero, BodyGen se saltea por
        ''' su gate "este actor no tiene ningún morph"; si va segundo, el <c>.psc</c> barre la key de BodyGen —
        ''' SSE <c>"RSMBodyGen"</c>, FO4 el keyword <c>None</c>). Con los dos tildados el .ini queda como RED para
        ''' los NPC del plugin que el usuario no re-grabó: ésos conservan su VMAD viejo, el script les llega
        ''' inerte, y el .ini es su única vía.</para>
        '''
        ''' <para>No aplica retroactivamente a actores ya spawneados — eso sólo lo alcanza el script.</para></summary>
        Public EmitBodyGen As Boolean

        ''' <summary>True cuando el apply-script es el DUEÑO de los body morphs: los emite y barre la key de
        ''' BodyGen antes de aplicar los suyos. Viaja al <c>.psc</c> como <c>MorphsOwned</c>.
        ''' <para>Va pegado a <see cref="EmitApplyScript"/>: si el script se emite, los morphs viajan en él. No
        ''' tiene control propio a propósito — no hay caso en que convenga emitir el script y dejarle los morphs
        ''' al .ini, porque el script gana igual y su barrido es lo ÚNICO que limpia lo que BodyGen dejó en el
        ''' co-save del jugador.</para>
        ''' <para>⛔ NO borra ni excluye nada del .ini (ver el comentario en NpcOverrideSaver, fase BodyGen).</para></summary>
        Public ReadOnly Property ScriptOwnsBodyMorphs As Boolean
            Get
                Return EmitApplyScript
            End Get
        End Property
        ''' <summary>When True the orchestrator attaches our Papyrus apply-script to each saved NPC_ via
        ''' VMAD (NpcVmadBuilder) and installs the compiled .pex, so the engine applies on first spawn the
        ''' RaceMenu/LooksMenu options with no other delivery route: body/hands/feet overlays, skin
        ''' overrides, and (SSE only) node transforms. Face overlays are NOT included — they are already
        ''' baked into the FaceGen textures, and re-applying them would composite them twice.
        ''' Default True (seeded from NPC_Config.EmitApplyScript).</summary>
        Public EmitApplyScript As Boolean
        ''' <summary>When True the orchestrator emits the outfits authored in the Edit Outfit "Create"
        ''' tab as OTFT records in this plugin (every dirty draft + the one this NPC's DOFT references).
        ''' When False no outfit is written and an NPC whose DOFT points at an unsaved draft falls back
        ''' to its original record outfit. Opt-in (default False) — outfits are only persisted alongside
        ''' an NPC save, never on their own.</summary>
        Public SaveNewOutfits As Boolean

        ''' <summary>Generacion del apply-script forzada a mano desde el dialogo. 0 = automatica (la del
        ''' sidecar + 1). Al forzarla, ese numero va al VMAD, al .pex parcheado Y al sidecar: los tres tienen
        ''' que ser el mismo o el script leeria properties que no existen.</summary>
        Public ScriptVersionOverride As Integer = 0

        ''' <summary>When True the saved NPC(s) are added to a Leveled NPC list (LVLN) written into the SAME
        ''' target plugin. Each saved NPC's GLOBAL FormID becomes one LVLO entry. Opt-in (default False).</summary>
        Public AddToLvlList As Boolean
        ''' <summary>True = create a NEW LVLN named <see cref="LvlListNewName"/>. False = append to the
        ''' EXISTING LVLN identified by <see cref="LvlListExistingEditorID"/> (which must live in the target
        ''' plugin — no cross-plugin). Only meaningful when <see cref="AddToLvlList"/> is True.</summary>
        Public LvlListIsNew As Boolean
        ''' <summary>Base name for a NEW list (ASCII; the saver writes it as <c>npcm_&lt;ESPNAME&gt;_LVLN_&lt;name&gt;</c>).
        ''' The first list keeps the base name; on overflow past 255 entries, sibling lists get <c>_1</c>,
        ''' <c>_2</c>, … appended (flat — no parent list).</summary>
        Public LvlListNewName As String
        ''' <summary>EditorID of the existing LVLN (in the target plugin) to append to. Matched by EditorID
        ''' in the saver against the LVLN the preserve-existing pass loads from the same plugin.</summary>
        Public LvlListExistingEditorID As String
        ''' <summary>When True, skip any saved NPC that is ALREADY a member of a Leveled NPC list (LVLN) in
        ''' THIS target plugin (the lists we manage — not load-order-wide). Opt-in (default False = add all,
        ''' allowing the same NPC to appear in multiple lists). Independent of new/existing mode.</summary>
        Public LvlListNoDuplicate As Boolean
    End Class

    Private ReadOnly _dataPath As String
    Private ReadOnly _existingPlugins As List(Of ExistingPlugin)
    Private ReadOnly _targetNpcFormID As UInteger
    Private ReadOnly _sourceMasterIsEsm As Boolean
    ' Save-execution dependencies — kept private so the form fully owns the run-the-save flow.
    Private ReadOnly _saveCtx As NpcOverrideSaver.SaveContext
    ''' <summary>The NPC currently selected/loaded — the default scope ("Selected").</summary>
    Private ReadOnly _selectedInput As NpcOverrideSaver.NpcSaveInput  ' anchor = first of _selectedInputs
    Private ReadOnly _selectedInputs As List(Of NpcOverrideSaver.NpcSaveInput)
    ''' <summary>Every NPC the user changed this session (includes the selected one). The
    ''' "Apply to all changed NPCs" checkbox switches the save scope to this list.</summary>
    Private ReadOnly _allDirtyInputs As List(Of NpcOverrideSaver.NpcSaveInput)
    ''' <summary>True when EVERY NPC in the current scope has the CharGen Face Preset flag, so the
    ''' bake is optional. Recomputed when the scope (Apply-to-all) toggles. When False the CharGen
    ''' checkbox is forced on (at least one NPC needs the BA2 to render in-world).</summary>
    Private _scopeAllowsChargenOptOut As Boolean

    Public Property Result As SaveTarget = Nothing
    ''' <summary>Populated by <see cref="OnOkClick"/> after the orchestrator finishes; remains
    ''' Nothing on Cancel. MainForm reads this after <c>ShowDialog</c> returns to perform
    ''' post-save cleanup (cache update, tree refresh, success MessageBox).</summary>
    Public Property ExecutionResult As NpcOverrideSaver.SaveExecutionResult = Nothing

    ''' <summary>Total number of high-level steps for the current save run. Computed at the
    ''' start of OnOkClick from the SaveTarget (depends on update-vs-new and CharGen yes/no).
    ''' Drives the determinate bar of the shared progress dialog so the user sees real progress
    ''' instead of a marquee.</summary>
    Private _totalSteps As Integer = 0
    Private _currentStep As Integer = 0
    ''' <summary>Ordered list of Phase-substring → step-number mappings. The orchestrator emits
    ''' free-form Phase strings; we match by substring (stable across minor wording changes)
    ''' to advance the counter. Built in OnOkClick once per run.</summary>
    Private _stepMap As List(Of (Match As String, StepNumber As Integer)) = Nothing
    ''' <summary>True for a multi-NPC ("All changed") run. The single-NPC determinate step plan
    ''' doesn't fit a batch, so batch runs drive the bar by NPC count (0..N) — advancing on each
    ''' "Baking CharGen" report — with "NPC k/N" in the detail. Single-NPC runs keep the step plan.</summary>
    Private _batchProgress As Boolean = False
    ''' <summary>NPC count for the current batch run; the determinate bar maximum.</summary>
    Private _batchNpcCount As Integer = 0
    ''' <summary>Last bar position reported in a batch run. Batch sub-phase reports (pack steps) update
    ''' the status text only and must leave the determinate bar where the last per-NPC "Baking CharGen"
    ''' report left it — the progress dialog's SetProgress sets both bar and text, so we re-pass these.</summary>
    Private _lastBatchCurrent As Integer = 0
    Private _lastBatchMax As Integer = 1

    ''' <summary>The plugin filename the anchor NPC is currently parented to in the MainForm tree.
    ''' Equals <c>selectedInput.SourcePluginName</c> = the plugin that wins the override post-merge.
    ''' Used by <see cref="PopulateExistingList"/> to pre-select EXACTLY this plugin when it appears
    ''' in the existing-auto-gen list (the user's expectation when re-saving an NPC whose override
    ''' already lives in a specific auto-gen plugin: the dialog defaults to THAT plugin, not "any
    ''' plugin that happens to contain this NPC"). Falls back to ContainsTargetNpc match, then to
    ''' index 0, when the anchor's source is a master or an unsaved plugin name.</summary>
    Private ReadOnly _anchorSourcePluginName As String

    Public Sub New(dataPath As String,
                   existingPlugins As List(Of ExistingPlugin),
                   selectedInputs As List(Of NpcOverrideSaver.NpcSaveInput),
                   allDirtyInputs As List(Of NpcOverrideSaver.NpcSaveInput),
                   sourceMasterIsEsm As Boolean,
                   saveCtx As NpcOverrideSaver.SaveContext,
                   Optional defaultToSelected As Boolean = False,
                   Optional anchorSourcePluginName As String = "")
        InitializeComponent()
        _baseWarningHeight = LabelWarning.Height
        _dataPath = dataPath
        _existingPlugins = If(existingPlugins, New List(Of ExistingPlugin)())
        _selectedInputs = If(selectedInputs, New List(Of NpcOverrideSaver.NpcSaveInput)())
        If _selectedInputs.Count = 0 Then Throw New ArgumentException("selectedInputs must have at least one entry", NameOf(selectedInputs))
        _selectedInput = _selectedInputs(0)
        _allDirtyInputs = If(allDirtyInputs, New List(Of NpcOverrideSaver.NpcSaveInput)())
        _targetNpcFormID = _selectedInput.NpcFormID
        _sourceMasterIsEsm = sourceMasterIsEsm
        _saveCtx = saveCtx
        _anchorSourcePluginName = If(anchorSourcePluginName, "")

        ' Scope radios: "Selected" vs "All changed". The default depends on the entry point: the
        ' toolbar Save button defaults to "All changed"; the tree context-menu "Save Selected"
        ' defaults to "Selected" (defaultToSelected:=True). Both labels ALWAYS show their count so the
        ' user knows exactly how many NPCs each scope will save.
        Dim dirtyCount = _allDirtyInputs.Count
        Dim selCount = _selectedInputs.Count
        RadioScopeAllChanged.Text = $"All changed ({dirtyCount})"
        RadioScopeSelected.Text = $"Selected ({selCount})"
        If defaultToSelected Then
            RadioScopeSelected.Checked = True
            RadioScopeAllChanged.Checked = False
        Else
            RadioScopeAllChanged.Checked = True
            RadioScopeSelected.Checked = False
        End If

        ' CharGen checkbox: default ON. When ANY NPC in the current scope has no CharGen Face Preset
        ' flag, the engine relies on CK's baked FaceGen — without our BA2 those NPCs render as a
        ' generic head — so the checkbox is forced True and disabled. When all NPCs in scope have the
        ' flag, the engine reconstructs at runtime, so the bake is optional (still defaults ON).
        CheckBoxGenerateChargen.Checked = True
        RecomputeChargenForcing()
        ' "Remove CharGen flag" is a sub-option of the bake — enabled only while the bake is on.
        ' Seed its checked state from the persisted per-app preference (default True) BEFORE wiring the
        ' toggle handler, so loading the saved value doesn't immediately re-persist it. RecomputeChargenForcing
        ' may have forced the bake on/off above; sync the sub-option's enabled state now, then keep it in sync
        ' on every bake toggle (incl. the programmatic ones from scope changes). The toggle handler persists
        ' the user's choice in-memory (flushed to npc_config.json on app close, same as the BA2 version).
        CheckBoxRemoveChargenFlag.Checked = NPC_Config.Current.RemoveCharGenFlagOnBake
        AddHandler CheckBoxGenerateChargen.CheckedChanged, AddressOf OnGenerateChargenChanged
        AddHandler CheckBoxRemoveChargenFlag.CheckedChanged, AddressOf OnRemoveChargenFlagChanged
        UpdateRemoveChargenFlagEnabled()

        ' The two "first spawn" deliveries — BodyGen .ini (body sliders) and the apply-script (overlays /
        ' skin / node transforms / BODY MORPHS). Both default True, both REMEMBERED, y son INDEPENDIENTES:
        ' desde que el script también entrega body morphs las cuatro combinaciones son válidas, porque el
        ' script gana por construcción (barre la key de BodyGen antes de aplicar la suya). Seed ANTES de
        ' enganchar los handlers, para que cargar un valor guardado no lo re-persista al toque
        ' (mismo patrón que CheckBoxRemoveChargenFlag arriba). Se vuelca a npc_config.json al cerrar la app.
        CheckBoxEmitBodyGen.Checked = NPC_Config.Current.EmitBodyGenIni

        ' El numeric del override tiene que mostrar SIEMPRE la generacion del plugin de destino ACTUAL, asi
        ' que se refresca con cualquier cosa que cambie ese destino, no solo al tildar el override.
        AddHandler ListBoxExisting.SelectedIndexChanged, AddressOf OnScriptVersionTargetChanged
        AddHandler TextBoxNewName.TextChanged, AddressOf OnScriptVersionTargetChanged
        AddHandler RadioButtonExisting.CheckedChanged, AddressOf OnScriptVersionTargetChanged
        RefreshScriptVersionDisplay()
        CheckBoxEmitApplyScript.Checked = NPC_Config.Current.EmitApplyScript
        RefreshApplyScriptLabel()   ' ⭐ al ABRIR tambien: la opcion se recuerda entre sesiones (ver su doc)
        AddHandler CheckBoxEmitBodyGen.CheckedChanged, AddressOf OnEmitBodyGenChanged
        AddHandler CheckBoxEmitApplyScript.CheckedChanged, AddressOf OnEmitApplyScriptChanged

        ' "Activate in load order": opt-out by default and remembered, same seed-before-wiring idiom as above.
        CheckBoxActivateInLoadOrder.Checked = NPC_Config.Current.ActivateInLoadOrder
        AddHandler CheckBoxActivateInLoadOrder.CheckedChanged, AddressOf OnActivateInLoadOrderChanged

        ' "Save new records": meaningful when the session has ANY unsaved (dirty) author-built draft — not
        ' only outfits, but also standalone armor (ARMO), armatures (ARMA), material swaps (MSWP) and leveled
        ' lists (LVLI). This ONE flag gates every draft-emission phase (ExecuteWritePhases 2c/2e/2f/2g), so if
        ' it only counted OutfitDrafts, a session that authored a skin/armor/material/leveled-list draft WITHOUT
        ' an outfit draft would leave the box disabled+unchecked and silently drop those drafts (and dangle any
        ' NPC.WNAM skin pointing at the dropped ARMO). Auto-check + enable when any kind is dirty. (The transient
        ' outfit preview sentinel is excluded.)
        Dim hasDirtyDrafts As Boolean = _saveCtx IsNot Nothing AndAlso (
            (_saveCtx.OutfitDrafts IsNot Nothing AndAlso _saveCtx.OutfitDrafts.Any(Function(d) d IsNot Nothing AndAlso d.IsDirty AndAlso d.FormID <> OutfitDraft.PreviewDraftFormID)) OrElse
            (_saveCtx.ArmoDrafts IsNot Nothing AndAlso _saveCtx.ArmoDrafts.Any(Function(d) d IsNot Nothing AndAlso d.IsDirty)) OrElse
            (_saveCtx.ArmaDrafts IsNot Nothing AndAlso _saveCtx.ArmaDrafts.Any(Function(d) d IsNot Nothing AndAlso d.IsDirty)) OrElse
            (_saveCtx.MswpDrafts IsNot Nothing AndAlso _saveCtx.MswpDrafts.Any(Function(d) d IsNot Nothing AndAlso d.IsDirty)) OrElse
            (_saveCtx.LeveledListDrafts IsNot Nothing AndAlso _saveCtx.LeveledListDrafts.Any(Function(d) d IsNot Nothing AndAlso d.IsDirty)))
        CheckBoxSaveNewOutfits.Enabled = hasDirtyDrafts
        CheckBoxSaveNewOutfits.Checked = hasDirtyDrafts
        CheckBoxSaveNewOutfits.Text = If(hasDirtyDrafts,
            "Save new records (outfits, armor, materials, leveled lists)",
            "Save new records  (none pending)")

        AddHandler RadioScopeAllChanged.CheckedChanged, AddressOf OnScopeChanged

        PopulateExistingList()
        ' Default to "create new" when no existing plugins, else "update existing".
        If _existingPlugins.Count > 0 Then
            RadioButtonExisting.Checked = True
            RadioButtonNew.Checked = False
        Else
            RadioButtonExisting.Enabled = False
            RadioButtonExisting.Text = RadioButtonExisting.Text & "  (none found)"
            RadioButtonNew.Checked = True
        End If

        ' Defaults for "Create new": no master flag, light flag on. ApplyFlagDefaultsForCreateNew
        ' is also the reset hook when the user toggles back from "Update existing" to "Create new".
        ApplyFlagDefaultsForCreateNew()

        AddHandler RadioButtonExisting.CheckedChanged, AddressOf OnRadioChanged
        AddHandler RadioButtonNew.CheckedChanged, AddressOf OnRadioChanged
        AddHandler ListBoxExisting.SelectedIndexChanged, AddressOf OnSelectionChanged
        AddHandler TextBoxNewName.TextChanged, AddressOf OnSelectionChanged
        ' Flag toggles refresh the warning (ESM/ESL flip on a plugin with new records is risky).
        AddHandler CheckBoxMarkAsMaster.CheckedChanged, AddressOf OnFlagChanged
        AddHandler CheckBoxLightMaster.CheckedChanged, AddressOf OnFlagChanged
        AddHandler ButtonOk.Click, AddressOf OnOkClick

        ' Leveled NPC list ("Add to LVL list"): default off. The existing-list combo is scoped to the
        ' SELECTED target plugin only (no cross-plugin) and refreshed whenever the plugin/mode changes.
        ' OnRadioChanged below (called at the end of New) runs the first RefreshLvlListUi.
        CheckBoxAddToLvlList.Checked = False
        RadioLvlNew.Checked = True
        AddHandler CheckBoxAddToLvlList.CheckedChanged, AddressOf OnLvlListChanged
        AddHandler RadioLvlNew.CheckedChanged, AddressOf OnLvlListChanged
        AddHandler RadioLvlExisting.CheckedChanged, AddressOf OnLvlListChanged

        PopulateEncodingCombo()
        InitBa2VersionCombo()

        OnRadioChanged(Nothing, EventArgs.Empty)
        UpdateWarning()
    End Sub

    ''' <summary>The NPCs the current scope will save: just the selected NPC when "Selected only" is
    ''' picked, else the full dirty list ("All changed", the default).</summary>
    Private Function CurrentInputs() As List(Of NpcOverrideSaver.NpcSaveInput)
        If RadioScopeSelected.Checked Then
            Return _selectedInputs
        End If
        Return _allDirtyInputs
    End Function

    ''' <summary>Recompute whether the CharGen bake can be opted out for the current scope. The bake
    ''' is forced on (checkbox checked + disabled) when ANY NPC in scope lacks the CharGen Face
    ''' Preset flag — those NPCs render as a generic head in-world without our BA2.</summary>
    Private Sub RecomputeChargenForcing()
        _scopeAllowsChargenOptOut = CurrentInputs().All(Function(i) i.IsCharGenFacePreset)
        ' Strip any prior "(required…)" suffix before re-deciding. Keep in sync with the Designer text.
        Const baseText As String = "Bake CharGen (NIF + textures) → BA2"
        If _scopeAllowsChargenOptOut Then
            CheckBoxGenerateChargen.Enabled = True
            CheckBoxGenerateChargen.Text = baseText
        Else
            CheckBoxGenerateChargen.Checked = True
            CheckBoxGenerateChargen.Enabled = False
            CheckBoxGenerateChargen.Text = baseText & "  (required: a NPC lacks CharGen flag)"
        End If
    End Sub

    ''' <summary>The "Remove CharGen flag" option only does something when the CharGen bake runs, so it
    ''' is enabled iff the bake checkbox is checked. The checked state is LEFT INTACT when disabling, so the
    ''' user's persisted preference is preserved (and stays visible); the BuildTargetFromUi gate makes a
    ''' checked-but-disabled state a no-op, so there is no need to force-uncheck (which would also clobber the
    ''' persisted preference by firing the toggle handler with False).</summary>
    Private Sub UpdateRemoveChargenFlagEnabled()
        CheckBoxRemoveChargenFlag.Enabled = CheckBoxGenerateChargen.Checked
    End Sub

    ''' <summary>Bake checkbox toggled (by the user or programmatically via RecomputeChargenForcing) —
    ''' refresh the dependent "Remove CharGen flag" sub-option's enabled state.</summary>
    Private Sub OnGenerateChargenChanged(sender As Object, e As EventArgs)
        UpdateRemoveChargenFlagEnabled()
    End Sub

    ''' <summary>"Remove CharGen flag" toggled — persist the choice on the in-memory NPC_Config singleton
    ''' (flushed to npc_config.json when MainForm closes, same mechanism as the BA2 version selector).</summary>
    Private Sub OnRemoveChargenFlagChanged(sender As Object, e As EventArgs)
        NPC_Config.Current.RemoveCharGenFlagOnBake = CheckBoxRemoveChargenFlag.Checked
    End Sub

    ''' <summary>"Emit BodyGen .ini" toggled — remember the choice (flushed to npc_config.json on app close,
    ''' same mechanism as the CharGen flag above).</summary>
    Private Sub OnEmitBodyGenChanged(sender As Object, e As EventArgs)
        NPC_Config.Current.EmitBodyGenIni = CheckBoxEmitBodyGen.Checked
    End Sub

    ''' <summary>La casilla del script ("Attach the helper script") cambió — se recuerda la elección.
    ''' <para>⛔⛔ ANTES SÓLO PERSISTÍA LA OPCIÓN, EN SILENCIO. Y destildarla es la acción más
    ''' destructiva del diálogo: el script es el ÚNICO transporte de todo lo que no se hornea — los overlays de cuerpo,
    ''' manos y pies, los skin overrides, cada hueso de Body Transform, y sobre todo el <b>magic</b>, que por diseño
    ''' nunca se hornea. Para el magic de cara es peor todavía: antes de esta tanda el pliegue lo metía en la textura,
    ''' así que había un segundo camino; ahora el pliegue lo excluye a propósito y si el script no va, no va nadie.
    ''' <para>El aviso es una sola vez por sesión y sólo al APAGARLA: no molesta a quien ya sabe lo que hace, y el que
    ''' la destildó sin saber se enteraba recién en el juego, sin nada que lo relacione con esta casilla.</para></para></summary>
    Private Sub OnEmitApplyScriptChanged(sender As Object, e As EventArgs)
        NPC_Config.Current.EmitApplyScript = CheckBoxEmitApplyScript.Checked
        RefreshApplyScriptLabel()
        If Not CheckBoxEmitApplyScript.Checked AndAlso Not _applyScriptOffWarned Then
            _applyScriptOffWarned = True
            MessageBox.Show(Me,
                "Without the helper script, anything that is not baked into the mesh or the texture stays in the app " &
                "and never reaches the game:" & ControlChars.Lf & ControlChars.Lf &
                "  •  tattoos on body, hands and feet, and the body paint layer" & ControlChars.Lf &
                "  •  every bone edit from Body Transform" & ControlChars.Lf &
                "  •  the body sliders — unless ""Emit BodyGen .ini"" is ticked, which delivers them too" & ControlChars.Lf &
                "  •  and ALL magic (spell effect) overlays, including magic face paint — those are never baked, so " &
                "the script is their only way in." & ControlChars.Lf & ControlChars.Lf &
                "The NPC still saves, and its face, body shape and equipment are unaffected." & ControlChars.Lf &
                "Tick the box again to keep them. If you do not want them, delete them in the editor instead — " &
                "then the preview matches the game." & ControlChars.Lf &
                "(Shown once per session.)",
                "The helper script is off", MessageBoxButtons.OK, MessageBoxIcon.Warning)
        End If
    End Sub

    ''' <summary>El rótulo dice el ESTADO, no sólo el nombre de la opción.
    ''' <para>⛔ EL AVISO SOLO SALTABA EN LA TRANSICIÓN, y la opción se RECUERDA entre sesiones: quien la destildó
    ''' hace un mes abría el diálogo, no veía nada, y se enteraba de la pérdida en el juego. Un estado peligroso
    ''' tiene que verse mientras DURA, no sólo cuando se entra en él. El patrón ya estaba resuelto tres bloques
    ''' más arriba, en <c>CheckBoxSaveNewOutfits</c> ("Save new records  (none pending)").</para></summary>
    Private Sub RefreshApplyScriptLabel()
        CheckBoxEmitApplyScript.Text = If(CheckBoxEmitApplyScript.Checked,
            "Attach the helper script (tattoos, body paint, bone edits, body sliders)",
            "Attach the helper script — OFF: tattoos, bone edits and body paint will NOT reach the game")
        CheckBoxEmitApplyScript.ForeColor = If(CheckBoxEmitApplyScript.Checked,
                                              SystemColors.ControlText, Drawing.Color.DarkGoldenrod)
    End Sub

    ''' <summary>One-shot del aviso de arriba. ⛔ <b>Shared</b>, no de instancia: era un campo del diálogo, así
    ''' que cerrar y reabrir el diálogo lo reponía y el aviso volvía, mientras el texto prometía "shown once per
    ''' session". Es de proceso, igual que los one-shots del pool de overlays.</summary>
    Private Shared _applyScriptOffWarned As Boolean

    ''' <summary>"Activate in load order" toggled — remember the choice.</summary>
    Private Sub OnActivateInLoadOrderChanged(sender As Object, e As EventArgs)
        NPC_Config.Current.ActivateInLoadOrder = CheckBoxActivateInLoadOrder.Checked
    End Sub

    ''' <summary>Scope radio toggle: recompute the CharGen forcing for the new scope and refresh the
    ''' warning hint. Wired to RadioScopeAllChanged.CheckedChanged (fires on every scope change).</summary>
    Private Sub OnScopeChanged(sender As Object, e As EventArgs)
        RecomputeChargenForcing()
        UpdateWarning()
    End Sub

    ''' <summary>Game-aware archive-target selector for the baked CharGen output. Both games show the
    ''' combo + label (SSE was previously hidden here).
    ''' FO4 — "BA2 version:", three options:
    '''   index 0 = v8 (Next Gen, default) · index 1 = v1 (Old Gen / universal)
    '''   index 2 = 0 (None / Loose) — skip BA2 pack entirely, leave the bake outputs as loose
    '''   Persists into NPC_Config.Ba2Version_FO4.
    ''' SSE — "Archive:", two options: index 0 = BSA (v105), index 1 = None / Loose.
    '''   Persists into NPC_Config.Archive_SSE (0 = Loose, 1 = BSA).
    ''' The loose-vs-pack decision is read game-aware at pack time via NPC_Config.IsLooseOnly.</summary>
    Private Sub InitBa2VersionCombo()
        Dim isSSE As Boolean = (Config_App.Current IsNot Nothing AndAlso Config_App.Current.Game = Config_App.Game_Enum.Skyrim)
        ' Populate + set selection BEFORE wiring the handler so this init does not write config back.
        If isSSE Then
            Ba2VersionUI.PopulateArchiveComboSSE(ComboBoxBa2Version)
            ComboBoxBa2Version.SelectedIndex = Ba2VersionUI.ArchiveSseToComboIndex(NPC_Config.Current.Archive_SSE)
            LabelBa2Version.Text = "Archive:"
        Else
            Ba2VersionUI.PopulateBa2VersionCombo(ComboBoxBa2Version, includeLoose:=True)
            ComboBoxBa2Version.SelectedIndex = Ba2VersionUI.Ba2VersionToComboIndex(NPC_Config.Current.Ba2Version_FO4)
            LabelBa2Version.Text = "BA2 version:"
        End If
        AddHandler ComboBoxBa2Version.SelectedIndexChanged, AddressOf OnBa2VersionChanged

        ' Both games: combo + label visible.
        LabelBa2Version.Visible = True
        ComboBoxBa2Version.Visible = True
    End Sub

    Private Sub OnBa2VersionChanged(sender As Object, e As EventArgs)
        If Config_App.Current IsNot Nothing AndAlso Config_App.Current.Game = Config_App.Game_Enum.Skyrim Then
            NPC_Config.Current.Archive_SSE = Ba2VersionUI.ComboIndexToArchiveSse(ComboBoxBa2Version.SelectedIndex)
        Else
            NPC_Config.Current.Ba2Version_FO4 = Ba2VersionUI.ComboIndexToBa2Version(ComboBoxBa2Version.SelectedIndex)
        End If
    End Sub

    ''' <summary>Encoding selector entries. Mirror of xEdit -cp-trans command-line param values
    ''' (xeInit.pas:1320) plus the per-language Auto option (mirror of xeInit.pas:1297 sLanguage
    ''' lookup). Default UTF-8 matches xeInit.pas:1122 wbLEncodingDefault[False] for FO4.</summary>
    Private NotInheritable Class EncodingOption
        Public Property Label As String
        ''' <summary>Code page string passed to PluginEncodingSettings.SetTranslatableOverride.
        ''' Empty means "use Auto sLanguage" (no override; whatever startup set stays in force).</summary>
        Public Property OverrideValue As String
        Public Overrides Function ToString() As String
            Return Label
        End Function
    End Class

    Private Sub PopulateEncodingCombo()
        ComboBoxEncoding.Items.Clear()

        Dim utf8 As New EncodingOption With {.Label = "UTF-8 (recommended — FO4 default)", .OverrideValue = "65001"}
        ComboBoxEncoding.Items.Add(utf8)
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Auto (sLanguage from Fallout4.ini)", .OverrideValue = ""})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1252 (Western European)", .OverrideValue = "1252"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1250 (Central European)", .OverrideValue = "1250"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1251 (Cyrillic / Russian)", .OverrideValue = "1251"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1253 (Greek)", .OverrideValue = "1253"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1254 (Turkish)", .OverrideValue = "1254"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1256 (Arabic)", .OverrideValue = "1256"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "CP949 (Korean UHC)", .OverrideValue = "949"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "CP932 (Japanese Shift-JIS)", .OverrideValue = "932"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "CP936 (Simplified Chinese GBK)", .OverrideValue = "936"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "CP950 (Traditional Chinese Big5)", .OverrideValue = "950"})

        ComboBoxEncoding.SelectedItem = utf8
    End Sub

    ''' <summary>Resolve the user's choice into the value passed to SetTranslatableOverride.
    ''' Empty means "leave the startup-applied Auto setting in place".</summary>
    Private Function GetSelectedEncodingOverride() As String
        Dim opt = TryCast(ComboBoxEncoding.SelectedItem, EncodingOption)
        If opt Is Nothing Then Return "65001"   ' fall back to UTF-8 if something went sideways
        Return opt.OverrideValue
    End Function


    ''' <summary>Reset the Master / Light checkboxes to the "Create new" defaults: plain ESP
    ''' (no master flag) with the Light flag on. Called at form construction and whenever the
    ''' user switches back from "Update existing" to "Create new".</summary>
    Private Sub ApplyFlagDefaultsForCreateNew()
        CheckBoxMarkAsMaster.Checked = False
        CheckBoxLightMaster.Checked = True
        ' "Create new" returns the encoding combo to the UTF-8 default (FO4 default per
        ' xeInit.pas:1122). User can still pick a different value before saving.
        SelectEncodingComboByCodePage(65001)
    End Sub

    ''' <summary>Sync the Master / Light checkboxes to whatever the selected existing plugin
    ''' actually has on disk. Called whenever the user picks a different plugin from the list,
    ''' so the saved file keeps the same flag set unless the user explicitly changes them.</summary>
    Private Sub ApplyFlagsFromExisting(ep As ExistingPlugin)
        If ep Is Nothing Then Return
        CheckBoxMarkAsMaster.Checked = ep.IsEsm
        CheckBoxLightMaster.Checked = ep.IsLight
        ' Auto-select the encoding combo to match the plugin's per-file <cp:XXXX> tag so the
        ' rewrite preserves it. Nothing on the ep means the plugin had no tag → default UTF-8
        ' (FO4 canonical default). User can override before clicking Save.
        Dim cp = If(ep.TranslatableEncoding IsNot Nothing, ep.TranslatableEncoding.CodePage, 65001)
        SelectEncodingComboByCodePage(cp)
    End Sub

    ''' <summary>Find the encoding combo item whose OverrideValue maps to the given code page
    ''' and select it. No-op if no match (e.g. an exotic code page we don't expose).</summary>
    Private Sub SelectEncodingComboByCodePage(codePage As Integer)
        If ComboBoxEncoding Is Nothing OrElse ComboBoxEncoding.Items.Count = 0 Then Return
        Dim target = codePage.ToString()
        For Each item In ComboBoxEncoding.Items
            Dim opt = TryCast(item, EncodingOption)
            If opt Is Nothing Then Continue For
            If opt.OverrideValue = target Then
                ComboBoxEncoding.SelectedItem = opt
                Return
            End If
        Next
    End Sub

    Private Sub PopulateExistingList()
        ListBoxExisting.BeginUpdate()
        ListBoxExisting.Items.Clear()
        ' Preselection priority — exact > heuristic > default:
        '   1) The plugin that hosts the anchor NPC in the MainForm tree (= its post-merge
        '      SourcePluginName). Re-saving an NPC from "NPC_Manager_3.esp" defaults to
        '      "NPC_Manager_3.esp", NOT to "NPC_Manager.esp" just because that plugin happens
        '      to also contain the NPC.
        '   2) Any auto-gen plugin that currently overrides the anchor (ContainsTargetNpc) —
        '      kicks in when the anchor's source is a master (Fallout4.esm etc.) so the tree
        '      parent is a master rather than an auto-gen plugin.
        '   3) Index 0 — first plugin alphabetically, deterministic fallback.
        Dim anchorMatchIndex As Integer = -1
        Dim containsMatchIndex As Integer = -1
        For i = 0 To _existingPlugins.Count - 1
            Dim ep = _existingPlugins(i)
            ListBoxExisting.Items.Add(ep)
            If anchorMatchIndex < 0 AndAlso _anchorSourcePluginName <> "" AndAlso
               String.Equals(ep.FileName, _anchorSourcePluginName, StringComparison.OrdinalIgnoreCase) Then
                anchorMatchIndex = i
            End If
            If containsMatchIndex < 0 AndAlso ep.ContainsTargetNpc Then containsMatchIndex = i
        Next
        If ListBoxExisting.Items.Count > 0 Then
            Dim preselectIndex As Integer
            If anchorMatchIndex >= 0 Then
                preselectIndex = anchorMatchIndex
            ElseIf containsMatchIndex >= 0 Then
                preselectIndex = containsMatchIndex
            Else
                preselectIndex = 0
            End If
            ListBoxExisting.SelectedIndex = preselectIndex
        End If
        ListBoxExisting.EndUpdate()
    End Sub

    Private Sub OnRadioChanged(sender As Object, e As EventArgs)
        Dim isExisting = RadioButtonExisting.Checked
        ListBoxExisting.Enabled = isExisting AndAlso _existingPlugins.Count > 0
        TextBoxNewName.Enabled = Not isExisting
        ' Sync the flag checkboxes: when entering "Update existing" mirror the currently-selected
        ' plugin's on-disk flags, when entering "Create new" reset to the new-plugin defaults.
        If isExisting Then
            ApplyFlagsFromExisting(TryCast(ListBoxExisting.SelectedItem, ExistingPlugin))
        Else
            ApplyFlagDefaultsForCreateNew()
        End If
        UpdateEncodingHint()
        UpdateWarning()
        RefreshLvlListUi()
    End Sub

    ''' <summary>
    ''' Make it visible in the UI that the encoding combo is auto-detected (preserved) from the
    ''' selected plugin in "Update existing" mode, vs a free choice in "Create new" mode. Without
    ''' this, the combo silently switches to e.g. "Windows-1251" and the user can't tell whether
    ''' that's their choice or came from the plugin.
    ''' </summary>
    Private Sub UpdateEncodingHint()
        If RadioButtonExisting.Checked Then
            LabelEncodingHint.Text = "(from plugin)"
        Else
            LabelEncodingHint.Text = ""
        End If
    End Sub

    Private Sub OnSelectionChanged(sender As Object, e As EventArgs)
        ' Re-sync flags when the user picks a different existing plugin. The text-box change
        ' on the "Create new" side hits this handler too but ApplyFlagsFromExisting bails on
        ' Nothing, so it's a no-op there.
        If RadioButtonExisting.Checked Then
            ApplyFlagsFromExisting(TryCast(ListBoxExisting.SelectedItem, ExistingPlugin))
        End If
        UpdateWarning()
        RefreshLvlListUi()
    End Sub

    ''' <summary>ESM/ESL checkbox toggled — refresh the warning so a risky flag flip surfaces live.</summary>
    Private Sub OnFlagChanged(sender As Object, e As EventArgs)
        UpdateWarning()
    End Sub

    Private Sub UpdateWarning()
        Dim warnings As New List(Of String)

        ' Hard block FIRST so its reason heads the band. "Update existing" onto a plugin that is not
        ' loaded cannot be done correctly: every FormID of its preserved records gets resolved by
        ' reading the file-local master index as a load-order slot, which names a DIFFERENT plugin —
        ' that is the spurious-master / broken-reference bug this gate exists to stop. Same for a
        ' loaded plugin whose own masters are absent. "Create new" is never blocked.
        Dim blockReason = ExistingTargetBlockReason()
        If blockReason <> "" Then warnings.Add(blockReason)
        ButtonOk.Enabled = (blockReason = "")

        If RadioButtonExisting.Checked Then
            Dim sel As ExistingPlugin = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
            If sel IsNot Nothing AndAlso sel.ContainsTargetNpc Then
                warnings.Add("This plugin already overrides the selected NPC — the existing override will be replaced.")
            End If
        End If

        ' Collision: target NPC already overridden in some OTHER auto-gen plugin.
        Dim collidingPlugins = _existingPlugins.
            Where(Function(p) p.ContainsTargetNpc).
            Select(Function(p) p.FileName).
            ToList()
        If collidingPlugins.Count > 0 Then
            warnings.Add("Also overridden in: " & String.Join(", ", collidingPlugins) &
                         " — last-loaded wins; consider updating that one.")
        End If

        ' ESM/ESL flag flip on an existing plugin that originates new records (OTFTs): flipping
        ' re-encodes those records' FormIDs (inherent to ESP↔ESL), breaking external references.
        If IsRiskyEslFlip() Then
            warnings.Add("⚠ Changing ESM/ESL re-encodes this plugin's NEW outfit (OTFT) FormIDs — existing saves/mods referencing them would break. (NPC overrides are unaffected.)")
        End If

        Dim text = String.Join(vbCrLf, warnings)
        LabelWarning.Text = text
        ' El aviso vive arriba a la derecha, en la fila de scope, y el ancho ahí es fijo. El texto
        ' completo tiene que quedar accesible aunque el label termine recortando.
        ToolTipWarning.SetToolTip(LabelWarning, text)
        GrowWarningBand()
    End Sub

    ''' <summary>Ajusta el alto de la banda del aviso al texto que hay, bajando los grupos si crece.
    ''' <para>⛔ MEDIDO, no estimado: el aviso del ESL flip ocupa DOS líneas al ancho de este label
    ''' (834 px de texto contra 646 de caja), así que los tres avisos juntos son CUATRO líneas —
    ''' 60 px de texto y 64 de caja para dibujarlas. Un label fijo de ese alto deja la cabecera
    ''' flotando lejos de los grupos en el caso normal, que es de una o dos líneas; y uno fijo de
    ''' dos líneas hacía desaparecer el aviso del ESL entero, que es justo el más grave.</para>
    ''' <para>Los botones y el check de abajo están anclados <c>Bottom</c>, así que se acomodan solos
    ''' al crecer el form; los cuatro GroupBox no tienen ancla y hay que bajarlos a mano.</para></summary>
    Private Sub GrowWarningBand()
        ' Un Label dibuja una línea de más de lo que mide TextRenderer: MEDIDO, 60 px de texto
        ' necesitan 64 px de caja para que se vean las cuatro líneas.
        Const boxPadding As Integer = 6
        Dim needed = If(LabelWarning.Text.Length = 0, 0,
                        TextRenderer.MeasureText(LabelWarning.Text, LabelWarning.Font,
                                                 New Size(LabelWarning.Width, Integer.MaxValue),
                                                 TextFormatFlags.WordBreak).Height + boxPadding)
        Dim target = Math.Max(_baseWarningHeight, needed)
        Dim shift = target - LabelWarning.Height
        If shift = 0 Then Return

        LabelWarning.Height = target
        ' Centrado con los radios mientras entra en la banda de diseño; cuando creció, el bloque
        ' arranca arriba y acompaña a la fila de scope en vez de descolgarse hacia abajo.
        LabelWarning.TextAlign = If(target > _baseWarningHeight,
                                    ContentAlignment.TopLeft, ContentAlignment.MiddleLeft)
        For Each g As Control In {GroupBoxTarget, GroupBoxSave, GroupBoxEncoding, GroupBoxLvlList}
            g.Top += shift
        Next
        Height += shift
    End Sub

    ''' <summary>Alto de diseño del label del aviso (dos líneas), piso de <see cref="GrowWarningBand"/>.
    ''' Se lee del Designer para no duplicar la constante en dos lados.</summary>
    Private ReadOnly _baseWarningHeight As Integer

    ''' <summary>Why the selected "Update existing" target cannot be written, or "" when it can.
    ''' <para>Mirrors xEdit's <c>mfMastersMissing</c> (wbLoadOrder.pas:404-421): a module whose masters
    ''' are not accounted for is presented as unusable rather than loaded on a guess. The list of
    ''' existing plugins comes from a raw disk sweep of Data\ (<see cref="ScanAutoGeneratedPlugins"/>),
    ''' which has no idea what the user actually ticked in the Preflight — so a target that was never
    ''' loaded can and does show up in it.</para>
    ''' <para>The message names the fix, because a disabled button with no way out is its own bug: the
    ''' plugin has to be ticked in the Preflight, which is where the load set is chosen.</para></summary>
    Private Function ExistingTargetBlockReason() As String
        If Not RadioButtonExisting.Checked Then Return ""
        Dim sel = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
        If sel Is Nothing Then Return ""
        Dim pm = If(_saveCtx Is Nothing, Nothing, _saveCtx.PluginManager)
        If pm Is Nothing Then Return ""

        If Not pm.IsLoaded(sel.FileName) Then
            Return "⛔ " & sel.FileName & " is not loaded, so its records cannot be re-mastered safely — " &
                   "saving onto it would add masters it does not use and point its references at the " &
                   "wrong plugins. Tick it in the Preflight (browse the Data folder again) and reopen " &
                   "this dialog, or use Create new instead."
        End If

        Dim missing = pm.MissingMastersOf(sel.FileName)
        If missing.Count > 0 Then
            Return "⛔ " & sel.FileName & " needs " & If(missing.Count = 1, "a master that is", "masters that are") &
                   " not loaded: " & String.Join(", ", missing) &
                   ". Its references cannot be resolved without them. Tick them in the Preflight, or " &
                   "use Create new instead."
        End If

        Return ""
    End Function

    ''' <summary>True when the user is updating an existing plugin, has changed its ESM or ESL flag
    ''' from the on-disk value, AND that plugin originates new records (OTFTs). Only then does the
    ''' flag flip re-encode FormIDs in a way that breaks external references — a pure NPC-override
    ''' plugin flips with zero FormID change (overrides keep their master FormID).</summary>
    Private Function IsRiskyEslFlip() As Boolean
        If Not RadioButtonExisting.Checked Then Return False
        Dim sel = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
        If sel Is Nothing Then Return False
        Dim flagChanged = (CheckBoxMarkAsMaster.Checked <> sel.IsEsm) OrElse (CheckBoxLightMaster.Checked <> sel.IsLight)
        If Not flagChanged Then Return False
        ' Prefer the value computed during the background Preflight scan (cache hit, no UI-thread
        ' load). Only plugins added to the cache post-save by MainForm lack it; those fall back below.
        If sel.HasNewSelfRecords.HasValue Then Return sel.HasNewSelfRecords.Value
        Return PluginHasNewSelfRecords(sel.FullPath)
    End Function

    ''' <summary>Whether a plugin file contains any record it ORIGINATES (a "self" record: file-local
    ''' FormID high byte ≥ the plugin's master count), as opposed to overrides of master records.
    ''' For NPC_Manager auto-gen plugins these are the new OTFT outfits. Result cached per path.
    ''' <para>Fallback path only: the fast path is <see cref="ExistingPlugin.HasNewSelfRecords"/>,
    ''' pre-computed off the UI thread during the Preflight scan. This synchronous reader.Load runs
    ''' only for plugins that bypassed that scan (e.g. added to the cache after a save).</para></summary>
    Private Function PluginHasNewSelfRecords(path As String) As Boolean
        Dim cached As Boolean
        If _hasNewRecordsCache.TryGetValue(path, cached) Then Return cached
        Dim result As Boolean = False
        Try
            Dim reader As New PluginReader()
            reader.Load(path)
            For Each kvp In reader.Records
                If (kvp.Key >> 24) >= CUInt(reader.Masters.Count) Then
                    result = True
                    Exit For
                End If
            Next
        Catch
        End Try
        _hasNewRecordsCache(path) = result
        Return result
    End Function

    Private ReadOnly _hasNewRecordsCache As New Dictionary(Of String, Boolean)(StringComparer.OrdinalIgnoreCase)

    ''' <summary>Validates the user's input, builds a <see cref="SaveTarget"/>. Returns Nothing
    ''' on validation failure (the user has been notified via MessageBox).</summary>
    Private Function BuildTargetFromUi() As SaveTarget
        Dim target As New SaveTarget With {
            .MarkAsMaster = CheckBoxMarkAsMaster.Checked,
            .LightMaster = CheckBoxLightMaster.Checked,
            .GenerateChargen = CheckBoxGenerateChargen.Checked,
            .RemoveCharGenFlag = CheckBoxGenerateChargen.Checked AndAlso CheckBoxRemoveChargenFlag.Checked,
            .EmitBodyGen = CheckBoxEmitBodyGen.Checked,
            .EmitApplyScript = CheckBoxEmitApplyScript.Checked,
            .SaveNewOutfits = CheckBoxSaveNewOutfits.Checked,
            .ScriptVersionOverride = If(CheckBoxOverrideScriptVersion.Checked, CInt(NumericUpDownScriptVersion.Value), 0)
        }

        If RadioButtonExisting.Checked Then
            Dim sel As ExistingPlugin = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
            If sel Is Nothing Then
                MessageBox.Show(Me, "Select an existing plugin or switch to 'Create new'.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                Return Nothing
            End If
            target.TargetPath = sel.FullPath
            target.IsNewPlugin = False
            target.ReplacingExistingNpc = sel.ContainsTargetNpc
        Else
            Dim baseName = TextBoxNewName.Text.Trim()
            If String.IsNullOrWhiteSpace(baseName) Then
                MessageBox.Show(Me, "Plugin name cannot be empty.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                Return Nothing
            End If
            If baseName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0 Then
                MessageBox.Show(Me, "Plugin name contains invalid characters.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                Return Nothing
            End If
            If baseName.EndsWith(".esp", StringComparison.OrdinalIgnoreCase) OrElse
               baseName.EndsWith(".esm", StringComparison.OrdinalIgnoreCase) OrElse
               baseName.EndsWith(".esl", StringComparison.OrdinalIgnoreCase) Then
                baseName = Path.GetFileNameWithoutExtension(baseName)
            End If
            Dim candidate = baseName & ".esp"
            Dim suffix = 2
            While File.Exists(Path.Combine(_dataPath, candidate))
                candidate = $"{baseName}_{suffix}.esp"
                suffix += 1
            End While
            target.TargetPath = Path.Combine(_dataPath, candidate)
            target.IsNewPlugin = True
            target.ReplacingExistingNpc = False
        End If

        ' Leveled NPC list ("Add to LVL list"): add the saved NPC(s) to a new or existing LVLN in the
        ' SAME target plugin. Existing lists are matched by EditorID against the target plugin's LVLN.
        If CheckBoxAddToLvlList.Checked Then
            target.AddToLvlList = True
            target.LvlListNoDuplicate = CheckBoxLvlNoDup.Checked
            If RadioLvlExisting.Checked Then
                Dim selLvl = TryCast(ComboBoxLvlExisting.SelectedItem, LvlnListInfo)
                If selLvl Is Nothing Then
                    MessageBox.Show(Me, "Select an existing leveled NPC list, or switch to 'New'.",
                                    "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                    Return Nothing
                End If
                target.LvlListIsNew = False
                target.LvlListExistingEditorID = selLvl.EditorID
            Else
                Dim lvlName = TextBoxLvlNewName.Text.Trim()
                If Not IsValidLvlListName(lvlName) Then
                    MessageBox.Show(Me, "The leveled NPC list name must be ASCII: letters, digits or underscore (no spaces or accents).",
                                    "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                    Return Nothing
                End If
                ' Collision with an existing LVLN in the target plugin? (Only update-existing can collide;
                ' a brand-new plugin has none.) Compare against the FINAL namespaced EditorID the saver writes
                ' (npcm_<ESPNAME>_LVLN_<name>) — same transform, so the check matches what lands on disk.
                Dim espNameNoExt = Path.GetFileNameWithoutExtension(target.TargetPath)
                Dim wouldBeEdid = NpcOverrideSaver.ApplyEspNamespaceToEditorId(NpcOverrideSaver.LeveledNpcListEditorIdPrefix & lvlName, espNameNoExt)
                If Not target.IsNewPlugin AndAlso
                   GetLvlnListsForPlugin(target.TargetPath).Any(Function(i) String.Equals(i.EditorID, wouldBeEdid, StringComparison.OrdinalIgnoreCase)) Then
                    MessageBox.Show(Me, $"A leveled NPC list '{wouldBeEdid}' already exists in this plugin." & vbCrLf &
                                    "Choose 'Existing' to add to it, or use a different name.",
                                    "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                    Return Nothing
                End If
                target.LvlListIsNew = True
                target.LvlListNewName = lvlName
            End If
        End If

        Return target
    End Function

    ''' <summary>OK handler. Validates, then runs the save orchestrator inside the shared modal
    ''' progress dialog (<see cref="BuildProgress_Form"/> — the same one Build CharGen loose uses).
    ''' The modal blocks this form automatically (no manual control-locking) and has no close box,
    ''' so the user can't tear it down mid-write. Closes this dialog with DialogResult.OK on success;
    ''' on failure the modal closes, this form is interactive again and the error is shown inline so
    ''' the user can adjust and retry. Not async: ShowDialog is blocking; the orchestrator await lives
    ''' inside the dialog's WorkAsync closure, which populates <see cref="ExecutionResult"/>.</summary>
    Private Sub OnOkClick(sender As Object, e As EventArgs)
        Dim target = BuildTargetFromUi()
        If target Is Nothing Then Return

        ' Confirm a risky ESM/ESL flag flip (existing plugin with new OTFT records) before writing —
        ' it re-encodes those records' FormIDs, breaking external references.
        If IsRiskyEslFlip() Then
            If MessageBox.Show(Me,
                "You changed the ESM/ESL flag of an existing plugin that contains new outfit (OTFT) records." & vbCrLf & vbCrLf &
                "Flipping the flag re-encodes those new records' FormIDs. Any existing savegame or other mod already referencing them would break. Your NPC overrides are NOT affected." & vbCrLf & vbCrLf &
                "Continue?",
                "ESM/ESL flag change", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) <> DialogResult.Yes Then
                Return
            End If
        End If

        Result = target

        ' Apply translatable-encoding override BEFORE BuildStepPlan / ExecuteAsync. The writer
        ' reads PluginEncodingSettings.Translatable inside EmitLString — once the write starts
        ' it's too late to change. Empty value means "Auto" (leave whatever MainForm_Load set
        ' from Fallout4.ini sLanguage in place). Mirror of xEdit -cp-trans command-line param.
        ' ⛔ ACOTADO AL GUARDADO. Antes era `SetTranslatableOverride`, que NO se restaura nunca: la
        ' elección del combo —una decisión transitoria de ESCRITURA— quedaba de global para el resto de la
        ' sesión. Guardar el NPC A en cp1251 hacía que el "Auto" del NPC B heredara cp1251, el sniff de
        ' SNAM/CNAM auto-detectara mal y EmitLString escribiera cp1251 dentro de un plugin UTF-8: el
        ' resultado del segundo guardado dependía del primero. El scope se cierra en el Finally de abajo,
        ' que es después de que ShowDialog volvió — o sea, con la escritura ya terminada.
        Dim encOverride = GetSelectedEncodingOverride()
        ' NOTE: encoding-conflict pre-check (FULL/SHRT/ATTX vs selected encoding, for the edited
        ' NPC + all pre-existing NPCs when updating) runs inside NpcOverrideSaver.ExecuteWritePhases
        ' right after the existing plugin is loaded — reusing that single PluginReader.Load instead
        ' of loading the plugin twice. A conflict aborts the save with a descriptive message.

        Dim inputs = CurrentInputs()
        BuildStepPlan(target, inputs.Count)
        _lastBatchCurrent = 0
        _lastBatchMax = Math.Max(1, _batchNpcCount)

        ' The CTS lives here (not inside the closure) so its lifetime spans ShowDialog: by the time
        ' the modal loop returns, every queued progress callback that touches it has been pumped, so
        ' disposing it afterwards can't race a late report.
        Dim cts As New System.Threading.CancellationTokenSource()
        ' ⛔ EL SCOPE SE ABRE PEGADO AL Try QUE LO CIERRA. Estaba 15 líneas más arriba, y entre medio corrían
        ' `CurrentInputs()`, `BuildStepPlan(...)` y el ctor del CTS: si cualquiera de esas tiraba, la excepción
        ' salía del handler del botón SIN pasar por el Finally y `_translatable` quedaba pisado con la elección
        ' del combo para el resto de la sesión — o sea, el defecto que este cambio arregla, reintroducido por
        ' el camino de error (WinForms deja la app viva tras el diálogo de excepción no manejada).
        ' Bajarlo hasta acá es seguro: el override lo lee `EmitLString` durante la ESCRITURA, y nada de lo de
        ' arriba escribe strings traducibles.
        Dim encScope = PluginEncodingSettings.PushTranslatableOverride(encOverride)
        Try
            Using prog As New BuildProgress_Form()
                prog.Text = If(inputs.Count > 1, $"Saving {inputs.Count} NPC overrides…", "Saving NPC override…")
                prog.WorkAsync =
                    Async Function(dlg As BuildProgress_Form) As Task
                        ' Let the dialog (Cancel button included) paint before the first blocking GL
                        ' bake — same rationale as the Build CharGen loose loop: a synchronous bake on
                        ' the UI thread otherwise leaves the dialog unpainted until it next yields.
                        Await Task.Delay(1)

                        Dim progress As New Progress(Of NpcOverrideSaver.SaveProgress)(
                            Sub(p)
                                ' Bridge the dialog's Cancel flag to the orchestrator's token. The bake
                                ' loop checks the token between NPCs, so cancel takes effect at the next
                                ' per-NPC boundary (same granularity as the old in-form Stop button).
                                If dlg.Cancelled AndAlso Not cts.IsCancellationRequested Then cts.Cancel()
                                ApplyProgressToDialog(dlg, p)
                            End Sub)
                        Try
                            ExecutionResult = Await NpcOverrideSaver.ExecuteAsync(
                                target, inputs, _saveCtx, progress, cts.Token)
                        Catch ex As Exception
                            ' ExecuteAsync wraps internal failures in ExecutionResult.ErrorMessage; this
                            ' Catch only fires for genuinely unexpected failures (e.g. ctor crash).
                            ExecutionResult = New NpcOverrideSaver.SaveExecutionResult With {
                                .Success = False,
                                .ErrorMessage = ex.Message
                            }
                        End Try
                    End Function
                prog.ShowDialog(Me)
            End Using
        Finally
            cts.Dispose()
            ' La encoding vuelve a lo que había ANTES de abrir este diálogo. Va acá y no más abajo porque
            ' la escritura ya terminó (ShowDialog es bloqueante) y lo que sigue —la activación en el load
            ' order— lee masters y flags de cabecera, no strings traducibles.
            encScope.Dispose()
        End Try

        If ExecutionResult IsNot Nothing AndAlso ExecutionResult.Success Then
            ' Load-order activation is a POST-SAVE step on purpose: the plugin has to exist on disk (the
            ' activator reads its masters + header flags from the file it is about to activate), and a failed
            ' save must never leave a dead entry in Plugins.txt.
            RunLoadOrderActivation(target)
            DialogResult = DialogResult.OK
            Close()
        Else
            ' Failure (or user-cancelled mid-batch): the modal closed, this dialog is interactive
            ' again — surface the error inline so the user can adjust and retry.
            Dim msg = "Save failed."
            If ExecutionResult IsNot Nothing AndAlso Not String.IsNullOrEmpty(ExecutionResult.ErrorMessage) Then
                msg = "Save failed: " & ExecutionResult.ErrorMessage
            End If
            MessageBox.Show(Me, msg, "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Error)
        End If
    End Sub

    ''' <summary>Turn the just-written plugin on in the game's Plugins.txt when the user asked for it. Silent
    ''' when it worked and there is nothing to warn about; a message box only when a guard stopped it, the write
    ''' failed, or the position can't be fixed by reordering (see <see cref="LoadOrderActivator"/>). Never
    ''' escalates: the save itself already succeeded, so nothing here can turn it into a failure.</summary>
    Private Sub RunLoadOrderActivation(target As SaveTarget)
        If Not CheckBoxActivateInLoadOrder.Checked Then Return
        Dim res = LoadOrderActivator.Activate(target.TargetPath)
        If Not res.NeedsAttention Then Return

        Dim body = res.Summary
        If res.Warning <> "" Then body &= vbCrLf & vbCrLf & res.Warning
        Dim icon = If(res.Kind = LoadOrderActivator.OutcomeKind.Failed, MessageBoxIcon.Error, MessageBoxIcon.Warning)
        MessageBox.Show(Me, body & vbCrLf & vbCrLf &
                        "The plugin itself was saved correctly — only the load order is affected." & vbCrLf &
                        "If you manage your load order with Mod Organizer or Vortex, activate it there.",
                        "Activate in load order", MessageBoxButtons.OK, icon)
    End Sub

    ''' <summary>Build the Phase→step map for the current SaveTarget. Phases are matched by
    ''' substring because the orchestrator's free-form strings include trailing ellipses and
    ''' contextual detail. Steps depend on:
    '''   - update-existing (adds "Loading existing plugin…") vs new plugin (skips it)
    '''   - GenerateChargen on (adds 4 bake/pack steps) vs off
    ''' Total ranges from 4 (new plugin, no chargen) to 9 (update existing + chargen).</summary>
    Private Sub BuildStepPlan(target As SaveTarget, npcCount As Integer)
        ' Batch runs (All changed): the bake phase repeats per NPC, which the fixed substring→step
        ' map can't represent, so the bar tracks NPC count (advanced in ApplyProgressToDialog) instead.
        _batchProgress = npcCount > 1
        _batchNpcCount = npcCount
        If _batchProgress Then
            _stepMap = New List(Of (Match As String, StepNumber As Integer))
            _totalSteps = 0
            _currentStep = 0
            Return
        End If

        Dim map As New List(Of (Match As String, StepNumber As Integer))
        Dim n As Integer = 0
        n += 1 : map.Add(("Preparing NPC record", n))
        If Not target.IsNewPlugin Then
            n += 1 : map.Add(("Loading existing plugin", n))
        End If
        n += 1 : map.Add(("Writing NPC override", n))
        n += 1 : map.Add(("Verifying written record", n))
        ' El sidecar va SIEMPRE (ver SaveTarget.WriteBssliders): no es opcional, es la base de datos de la app.
        n += 1 : map.Add(("Writing .bssliders sidecar", n))
        If target.EmitBodyGen Then
            n += 1 : map.Add(("Writing BodyGen", n))
        End If
        If target.EmitApplyScript Then
            n += 1 : map.Add(("Writing helper script", n))
        End If
        If target.GenerateChargen Then
            n += 1 : map.Add(("Baking CharGen", n))
            n += 1 : map.Add(("Compressing FaceGen bundle", n))
            n += 1 : map.Add(("Writing BA2", n))
            n += 1 : map.Add(("Removing loose files", n))
        End If
        ' "Done." is reported by the packer on the chargen path; on the no-chargen path the
        ' orchestrator just returns. Either way we want the final tick when work completes,
        ' so we map "Done" to (n+1) and bump the total to include it.
        n += 1 : map.Add(("Done", n))
        _stepMap = map
        _totalSteps = n
        _currentStep = 0
    End Sub

    ''' <summary>Resolve the step number for a Phase string by first-substring match against
    ''' the plan. Returns 0 if no entry matches (orchestrator may emit detail-only updates we
    ''' don't want to advance on — e.g. "Removed 3/8" sub-progress reuses the parent phase).</summary>
    Private Function ResolveStep(phase As String) As Integer
        If _stepMap Is Nothing OrElse String.IsNullOrEmpty(phase) Then Return 0
        For Each entry In _stepMap
            If phase.Contains(entry.Match, StringComparison.OrdinalIgnoreCase) Then
                Return entry.StepNumber
            End If
        Next
        Return 0
    End Function

    ''' <summary>Maps an orchestrator SaveProgress report onto the shared <see cref="BuildProgress_Form"/>'s
    ''' determinate bar + single status line. Single-NPC runs track the step plan ("Step k/N: phase");
    ''' batch runs track the NPC count, advancing the bar only on the per-NPC "Baking CharGen" report
    ''' while pack sub-steps update the text only. Marshaled to the UI thread by Progress(Of T), so it
    ''' touches the dialog directly; SetProgress forces the synchronous repaint the GL bake would
    ''' otherwise starve.</summary>
    Private Sub ApplyProgressToDialog(dlg As BuildProgress_Form, p As NpcOverrideSaver.SaveProgress)
        If p Is Nothing OrElse dlg Is Nothing Then Return
        Dim phase = If(p.Phase, "")
        Dim detail = If(p.Detail, "")

        If _batchProgress Then
            ' Batch: the bar tracks NPC count. Advance it only on the per-NPC "Baking CharGen" report
            ' (Determinate, Max=N, Current=k); the per-NPC pack sub-steps and the fast write phase
            ' update the text only — re-pass the last bar position so SetProgress leaves it put.
            If p.Determinate AndAlso p.Max > 0 AndAlso phase.Contains("Baking CharGen", StringComparison.OrdinalIgnoreCase) Then
                _lastBatchMax = Math.Max(1, p.Max)
                _lastBatchCurrent = Math.Max(0, Math.Min(p.Current, _lastBatchMax))
            End If
            dlg.SetProgress(_lastBatchCurrent, _lastBatchMax, ComposeStatus(phase, detail))
        Else
            Dim resolved = ResolveStep(phase)
            ' Steps only move forward — guards against out-of-order reports.
            If resolved > 0 AndAlso resolved > _currentStep Then _currentStep = resolved
            Dim shownStep As Integer = Math.Max(_currentStep, 1)
            dlg.SetProgress(_currentStep, Math.Max(1, _totalSteps),
                            ComposeStatus($"Step {shownStep}/{_totalSteps}: {phase}", detail))
        End If
    End Sub

    ''' <summary>Join the phase headline and optional sub-detail into the single status line the
    ''' shared progress dialog exposes (it has no separate detail label, unlike the old embedded panel).</summary>
    Private Shared Function ComposeStatus(headline As String, detail As String) As String
        If String.IsNullOrEmpty(detail) Then Return headline
        Return headline & " — " & detail
    End Function

    ' ============================================================================
    ' Leveled NPC list ("Add to LVL list") helpers.
    ' ============================================================================

    ''' <summary>One LVLN (Leveled NPC) record found in the selected target plugin — a candidate to add the
    ''' saved NPCs to. Matched in the saver by <see cref="EditorID"/> (unique within a plugin).</summary>
    Public Class LvlnListInfo
        Public EditorID As String
        Public EntryCount As Integer
        Public Overrides Function ToString() As String
            Return $"{EditorID}  ({EntryCount} NPC{If(EntryCount = 1, "", "s")})"
        End Function
    End Class

    ''' <summary>Guards <see cref="RefreshLvlListUi"/> against the CheckedChanged re-entrancy it triggers
    ''' when it forces RadioLvlNew on (so the body runs once per user action, not recursively).</summary>
    Private _suppressLvlEvents As Boolean = False
    ''' <summary>Per-plugin LVLN list cache, populated on demand from disk. The dialog is reconstructed on
    ''' every open (fresh cache), so each open reflects the current on-disk plugin — including lists this
    ''' feature wrote in a prior save. Not invalidated within one dialog lifetime (a successful save closes
    ''' the dialog, so a list can't be added mid-session). Keyed by full path, case-insensitive.</summary>
    Private ReadOnly _lvlnCache As New Dictionary(Of String, List(Of LvlnListInfo))(StringComparer.OrdinalIgnoreCase)

    Private Sub OnLvlListChanged(sender As Object, e As EventArgs)
        RefreshLvlListUi()
    End Sub

    ''' <summary>Repopulate the existing-list combo from the selected target plugin and set the enabled
    ''' states of the LVLN sub-controls. Existing mode is only offered when "Add to LVL list" is on AND
    ''' the selected target plugin actually has LVLN records; otherwise New is forced.</summary>
    Private Sub RefreshLvlListUi()
        If _suppressLvlEvents Then Return
        _suppressLvlEvents = True
        Try
            Dim addOn = CheckBoxAddToLvlList.Checked
            RefreshLvlExistingCombo()
            Dim hasExisting = ComboBoxLvlExisting.Items.Count > 0
            ' Force New when Existing isn't available (no LVLN in the selected plugin, or Create-new mode).
            If addOn AndAlso RadioLvlExisting.Checked AndAlso Not hasExisting Then RadioLvlNew.Checked = True
            RadioLvlNew.Enabled = addOn
            RadioLvlExisting.Enabled = addOn AndAlso hasExisting
            TextBoxLvlNewName.Enabled = addOn AndAlso RadioLvlNew.Checked
            ComboBoxLvlExisting.Enabled = addOn AndAlso RadioLvlExisting.Checked AndAlso hasExisting
            LabelLvlNewHint.Enabled = addOn
            CheckBoxLvlNoDup.Enabled = addOn
        Finally
            _suppressLvlEvents = False
        End Try
    End Sub

    ''' <summary>Fill the existing-LVLN combo from the currently-selected target plugin (none in Create-new
    ''' mode). Preserves the prior selection by EditorID when possible, else selects the first entry.</summary>
    Private Sub RefreshLvlExistingCombo()
        Dim prev = TryCast(ComboBoxLvlExisting.SelectedItem, LvlnListInfo)
        Dim prevEdid = If(prev IsNot Nothing, prev.EditorID, "")
        ComboBoxLvlExisting.BeginUpdate()
        ComboBoxLvlExisting.Items.Clear()
        Dim path = SelectedTargetPluginPathForLvl()
        If path <> "" Then
            For Each info In GetLvlnListsForPlugin(path)
                ComboBoxLvlExisting.Items.Add(info)
            Next
        End If
        If ComboBoxLvlExisting.Items.Count > 0 Then
            Dim sel As Integer = 0
            If prevEdid <> "" Then
                For i = 0 To ComboBoxLvlExisting.Items.Count - 1
                    Dim it = TryCast(ComboBoxLvlExisting.Items(i), LvlnListInfo)
                    If it IsNot Nothing AndAlso String.Equals(it.EditorID, prevEdid, StringComparison.OrdinalIgnoreCase) Then
                        sel = i
                        Exit For
                    End If
                Next
            End If
            ComboBoxLvlExisting.SelectedIndex = sel
        End If
        ComboBoxLvlExisting.EndUpdate()
    End Sub

    ''' <summary>Full path of the plugin the LVLN would be written into: the selected existing plugin when
    ''' updating, or "" for Create-new (a fresh plugin has no existing LVLN to choose from).</summary>
    Private Function SelectedTargetPluginPathForLvl() As String
        If RadioButtonExisting.Checked Then
            Dim sel = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
            If sel IsNot Nothing Then Return sel.FullPath
        End If
        Return ""
    End Function

    ''' <summary>Read the LVLN records (EditorID + LVLO count) from a plugin file. Cached per path so
    ''' switching the combo doesn't re-read. Best-effort: a malformed plugin yields an empty list.</summary>
    Private Function GetLvlnListsForPlugin(path As String) As List(Of LvlnListInfo)
        Dim cached As List(Of LvlnListInfo) = Nothing
        If _lvlnCache.TryGetValue(path, cached) Then Return cached
        Dim result As New List(Of LvlnListInfo)
        Try
            Dim reader As New PluginReader()
            reader.Load(path)
            For Each kvp In reader.Records
                Dim rec = kvp.Value
                If rec.Header.Signature <> "LVLN" Then Continue For
                Dim edid = If(rec.EditorID, "")
                If edid = "" Then Continue For
                Dim cnt = rec.Subrecords.Where(Function(sr) sr.Signature = "LVLO").Count()
                result.Add(New LvlnListInfo With {.EditorID = edid, .EntryCount = cnt})
            Next
        Catch
            ' Unreadable plugin — leave the list empty (the combo just won't offer existing lists).
        End Try
        result.Sort(Function(a, b) String.Compare(a.EditorID, b.EditorID, StringComparison.OrdinalIgnoreCase))
        _lvlnCache(path) = result
        Return result
    End Function

    ''' <summary>True when the name is a valid Leveled-NPC-list base name: non-empty and ASCII letters,
    ''' digits or underscore only (so the resulting EditorID is a clean zstring with no encoding pitfalls).</summary>
    Private Shared Function IsValidLvlListName(name As String) As Boolean
        If String.IsNullOrEmpty(name) Then Return False
        For Each c In name
            Dim ok = (c >= "a"c AndAlso c <= "z"c) OrElse
                     (c >= "A"c AndAlso c <= "Z"c) OrElse
                     (c >= "0"c AndAlso c <= "9"c) OrElse
                     c = "_"c
            If Not ok Then Return False
        Next
        Return True
    End Function


    ''' <summary>Habilita el numeric y le muestra la generacion QUE SE VA A GRABAR (la del sidecar + 1), para
    ''' que el numero que se ve sea el real antes de tocarlo. Se refresca al abrir el dialogo y al tildar el
    ''' override — que son los dos momentos en que importa.</summary>
    Private Sub CheckBoxOverrideScriptVersion_CheckedChanged(sender As Object, e As EventArgs) Handles CheckBoxOverrideScriptVersion.CheckedChanged
        NumericUpDownScriptVersion.Enabled = CheckBoxOverrideScriptVersion.Checked
        RefreshScriptVersionDisplay()
    End Sub

    Private Sub RefreshScriptVersionDisplay()
        Try
            Dim espPath = CurrentTargetPathOrNull()
            Dim prev = 0
            If Not String.IsNullOrEmpty(espPath) Then
                Dim sc = BssliderSidecar.Read(BssliderSidecar.BuildPath(espPath))
                If sc IsNot Nothing Then prev = sc.PayloadGeneration
            End If
            Dim nextGen = PexPatcher.NextGeneration(prev)
            If nextGen < CInt(NumericUpDownScriptVersion.Minimum) Then nextGen = CInt(NumericUpDownScriptVersion.Minimum)
            If nextGen > CInt(NumericUpDownScriptVersion.Maximum) Then nextGen = CInt(NumericUpDownScriptVersion.Maximum)
            NumericUpDownScriptVersion.Value = nextGen
        Catch
            ' Informativo: si no se puede leer el sidecar el numeric queda como esta. El valor REAL lo
            ' resuelve el guardado, salvo que el override este tildado.
        End Try
    End Sub

    ''' <summary>Path del ESP de destino segun el estado actual del dialogo, o Nothing si todavia no se puede
    ''' resolver. Mismo criterio que BuildTargetFromUi.</summary>
    Private Function CurrentTargetPathOrNull() As String
        Try
            If RadioButtonExisting.Checked Then
                Dim sel As ExistingPlugin = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
                Return If(sel Is Nothing, Nothing, sel.FullPath)
            End If
            Dim baseName = TextBoxNewName.Text.Trim()
            If baseName.Length = 0 Then Return Nothing
            If baseName.EndsWith(".esp", StringComparison.OrdinalIgnoreCase) OrElse
               baseName.EndsWith(".esm", StringComparison.OrdinalIgnoreCase) OrElse
               baseName.EndsWith(".esl", StringComparison.OrdinalIgnoreCase) Then
                baseName = Path.GetFileNameWithoutExtension(baseName)
            End If
            Return Path.Combine(_dataPath, baseName & ".esp")
        Catch
            Return Nothing
        End Try
    End Function


    ''' <summary>Cambio el plugin de destino ⇒ el numero mostrado ya no corresponde. Se refresca INCLUSO con el
    ''' override tildado, a proposito: si no, un valor tipeado para el plugin A se grabaria en el B, y si B ya
    ''' estaba en una generacion mas alta eso seria RETROCEDER — sus jugadores recibirian el payload rancio. Que
    ''' el usuario tenga que re-tipear es molesto; escribir una generacion vieja en silencio es un bug.</summary>
    Private Sub OnScriptVersionTargetChanged(sender As Object, e As EventArgs)
        RefreshScriptVersionDisplay()
    End Sub

End Class
