Imports System.IO
Imports FO4_Base_Library

''' <summary>
''' Dialog for "Save ESP/ESM" — picks a target plugin (existing auto-generated or new)
''' and the light-master flag. Scans the Data\ folder for plugins whose TES4.CNAM matches
''' the NPC_Manager canonical author string and lists them as "update existing" candidates.
''' </summary>
Public Class SaveEsp_Form

    ' ============================================================================
    ' Shared scan helpers (used by both Preflight_Form to populate the cache up-front
    ' during the splash, and by MainForm to re-scan if needed).
    ' ============================================================================

    ''' <summary>Full disk scan for NPC_Manager auto-generated plugins. Walks Data\, filters by
    ''' TES4.CNAM matching <see cref="PluginWriter.NPC_MANAGER_AUTHOR_CNAM"/>, then loads each
    ''' match to enumerate its NPC overrides. Best-effort: malformed plugins are skipped silently.
    '''
    ''' Designed to run during Preflight (splash screen) so the first Save ESP dialog opens
    ''' instantly. Reports progress via the optional <paramref name="progress"/> callback.</summary>
    Public Shared Function ScanAutoGeneratedPlugins(dataPath As String, Optional progress As IProgress(Of String) = Nothing) As List(Of ExistingPlugin)
        Dim result As New List(Of ExistingPlugin)
        If String.IsNullOrEmpty(dataPath) OrElse Not Directory.Exists(dataPath) Then Return result

        Dim pluginFiles = Directory.GetFiles(dataPath, "*.esp").
            Concat(Directory.GetFiles(dataPath, "*.esm")).
            Concat(Directory.GetFiles(dataPath, "*.esl")).
            ToList()

        Dim total = pluginFiles.Count
        Dim idx As Integer = 0
        For Each filePath In pluginFiles
            idx += 1
            Try
                Dim author = TryReadTes4Author(filePath)
                If author Is Nothing OrElse Not String.Equals(author, PluginWriter.NPC_MANAGER_AUTHOR_CNAM, StringComparison.Ordinal) Then
                    Continue For
                End If

                progress?.Report($"Scanning auto-generated plugins ({idx}/{total}): {Path.GetFileName(filePath)}")

                Dim reader As New PluginReader()
                reader.Load(filePath)
                Dim npcIds As New HashSet(Of UInteger)
                For Each kvp In reader.Records
                    If kvp.Value.Header.Signature = "NPC_" Then npcIds.Add(kvp.Key)
                Next
                Dim ep As New ExistingPlugin With {
                    .FullPath = filePath,
                    .FileName = Path.GetFileName(filePath),
                    .NpcCount = npcIds.Count,
                    .NpcFormIDs = npcIds,
                    .ContainsTargetNpc = False,
                    .IsEsm = reader.IsESM,
                    .IsLight = reader.IsESL,
                    .TranslatableEncoding = reader.TranslatableEncoding
                }
                result.Add(ep)
            Catch
                ' Plugin failed to read or open — skip silently.
            End Try
        Next
        Return result
    End Function

    ''' <summary>Read just the TES4 CNAM (author string) from a plugin file. Returns Nothing
    ''' if the plugin is malformed or has no author. Cheap: only reads the TES4 record body
    ''' (typically &lt; 1 KB) so the scan can dismiss most plugins without loading them.</summary>
    Public Shared Function TryReadTes4Author(path As String) As String
        Try
            Using fs As New FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read)
                Using br As New BinaryReader(fs)
                    ' TES4 record header layout (24 bytes total):
                    '   +0  sig "TES4" (4)
                    '   +4  DataSize u32 (4)
                    '   +8  Flags u32 (4)
                    '   +12 FormID u32 (4)
                    '   +16 VCS1 u32 (4)
                    '   +20 Version u16 (2)
                    '   +22 VCS2 u16 (2)
                    ' After reading sig+DataSize (8 bytes consumed), skip 16 more to land at body.
                    Dim sig = System.Text.Encoding.ASCII.GetString(br.ReadBytes(4))
                    If sig <> "TES4" Then Return Nothing
                    Dim dataSize = br.ReadUInt32()
                    fs.Seek(16, SeekOrigin.Current)
                    Dim bodyEnd = fs.Position + CLng(dataSize)

                    ' Two-pass to honor per-file SNAM <cp:XXXX> tag (xEdit flEncodingTrans):
                    ' first scan locates CNAM bytes + SNAM tag, then decodes CNAM with the
                    ' per-file encoding when present. xEdit canonical FO4 order is CNAM before
                    ' SNAM, so the on-disk CNAM is reached first while seeking — buffer its
                    ' bytes and resolve later. ASCII-only author literals are encoding-invariant
                    ' so the typical NPC_Manager scan path works either way; this loop is the
                    ' robust path for tooling that ever writes non-ASCII authors.
                    Dim cnamBytes As Byte() = Nothing
                    Dim perFileEnc As System.Text.Encoding = Nothing

                    While fs.Position <= bodyEnd - 6
                        Dim subSig = System.Text.Encoding.ASCII.GetString(br.ReadBytes(4))
                        Dim subSize = br.ReadUInt16()
                        If subSig = "CNAM" Then
                            cnamBytes = br.ReadBytes(CInt(subSize))
                        ElseIf subSig = "SNAM" Then
                            Dim snamBytes = br.ReadBytes(CInt(subSize))
                            Dim snamLen = snamBytes.Length
                            If snamLen > 0 AndAlso snamBytes(snamLen - 1) = 0 Then snamLen -= 1
                            Dim snamText = PluginEncodingSettings.DecodeTranslatable(snamBytes, 0, snamLen)
                            perFileEnc = PluginEncodingSettings.ParseSnamCpTag(snamText)
                            ' CNAM seen first per xEdit canonical order — we have what we need.
                            If cnamBytes IsNot Nothing Then Exit While
                        Else
                            fs.Seek(CLng(subSize), SeekOrigin.Current)
                        End If
                    End While

                    If cnamBytes Is Nothing Then Return Nothing
                    Dim cnamLen = cnamBytes.Length
                    If cnamLen > 0 AndAlso cnamBytes(cnamLen - 1) = 0 Then cnamLen -= 1
                    If perFileEnc IsNot Nothing Then
                        Return PluginEncodingSettings.DecodeWithEncoding(cnamBytes, 0, cnamLen, perFileEnc)
                    End If
                    Return PluginEncodingSettings.DecodeTranslatable(cnamBytes, 0, cnamLen)
                End Using
            End Using
        Catch
            Return Nothing
        End Try
        Return Nothing
    End Function

    ''' <summary>An auto-generated plugin found on disk that the user can update.</summary>
    Public Class ExistingPlugin
        Public FileName As String
        Public FullPath As String
        Public NpcCount As Integer
        ''' <summary>FormIDs of the NPC_ overrides this plugin contains. Captured at scan time
        ''' so the cache can answer ContainsTargetNpc for any target NPC without re-reading
        ''' the plugin from disk.</summary>
        Public NpcFormIDs As HashSet(Of UInteger)
        Public ContainsTargetNpc As Boolean
        ''' <summary>TES4 header flags read at scan time. Used by the dialog to auto-populate
        ''' the Master / Light checkboxes when the user picks "Update existing", so the saved
        ''' plugin keeps the same flag set unless the user explicitly changes them.</summary>
        Public IsEsm As Boolean
        Public IsLight As Boolean
        ''' <summary>Per-file translatable encoding parsed from the plugin's TES4 SNAM
        ''' &lt;cp:XXXX&gt; tag at scan time. Nothing when the plugin has no tag (default →
        ''' global Translatable). Used by the Save dialog to auto-select the encoding combo
        ''' when the user picks "Update existing", so the rewrite keeps the same encoding
        ''' the file originally had unless the user explicitly changes it.</summary>
        Public TranslatableEncoding As System.Text.Encoding

        Public Overrides Function ToString() As String
            Dim suffix As String = ""
            If ContainsTargetNpc Then
                suffix = "  (already contains this NPC — will be replaced)"
            ElseIf NpcCount > 0 Then
                suffix = $"  ({NpcCount} NPC override{If(NpcCount = 1, "", "s")})"
            End If
            Return $"{FileName}{suffix}"
        End Function
    End Class

    ''' <summary>Result of the dialog when the user clicks Save.</summary>
    Public Class SaveTarget
        Public TargetPath As String
        Public IsNewPlugin As Boolean
        ''' <summary>TES4 header ESM flag (0x01). When False the file is written as a plain
        ''' ESP without the master flag. Independent of <see cref="LightMaster"/>.</summary>
        Public MarkAsMaster As Boolean
        Public LightMaster As Boolean
        Public ReplacingExistingNpc As Boolean
        ''' <summary>When True the caller should bake the CharGen NIF + textures and pack
        ''' them into <c>&lt;plugin&gt; - Main.ba2</c> + <c>&lt;plugin&gt; - Textures.ba2</c> after
        ''' writing the override. Default True. Forced True (read-only) when the source NPC
        ''' has no CharGen Face Preset flag — those NPCs the engine bakes via CK and the BA2
        ''' is the only way they render in-world without a CK pass.</summary>
        Public GenerateChargen As Boolean
        ''' <summary>When True the orchestrator writes (or refreshes) the BodyMorphs/Skin sidecar
        ''' (<c>&lt;plugin&gt;.bssliders</c>) next to the ESP after the plugin is written. The
        ''' sidecar carries F4SE-only fields that have no record equivalent so re-opening the
        ''' ESP in NPC_Manager restores the slider state. Default True.</summary>
        Public WriteBssliders As Boolean
        ''' <summary>When True the orchestrator emits the F4SE BodyGen .ini pair
        ''' (<c>Data\F4SE\Plugins\F4EE\BodyGen\&lt;plugin&gt;\templates.ini</c> +
        ''' <c>morphs.ini</c>) so LooksMenu applies the sliders to NPCs on first-load in NEW
        ''' saves. Opt-in (default False); does not apply retroactively to actors already
        ''' spawned in a saved game.</summary>
        Public EmitBodyGen As Boolean
    End Class

    Private ReadOnly _dataPath As String
    Private ReadOnly _existingPlugins As List(Of ExistingPlugin)
    Private ReadOnly _targetNpcFormID As UInteger
    Private ReadOnly _sourceMasterIsEsm As Boolean
    Private ReadOnly _npcIsCharGenFacePreset As Boolean
    ' Save-execution dependencies — kept private so the form fully owns the run-the-save flow.
    Private ReadOnly _saveCtx As NpcOverrideSaver.SaveContext
    Private ReadOnly _saveNpc As NPC_Data
    Private ReadOnly _saveRawRecord As PluginRecord
    Private ReadOnly _saveRawNpcSpec As NPC_Data
    Private ReadOnly _saveSourcePluginName As String
    Private ReadOnly _saveBaseStateValid As Boolean
    Private ReadOnly _saveBaseStateWeightThin As Single
    Private ReadOnly _saveBaseStateWeightMuscular As Single
    Private ReadOnly _saveBaseStateWeightFat As Single

    Public Property Result As SaveTarget = Nothing
    ''' <summary>Populated by <see cref="OnOkClick"/> after the orchestrator finishes; remains
    ''' Nothing on Cancel. MainForm reads this after <c>ShowDialog</c> returns to perform
    ''' post-save cleanup (cache update, tree refresh, success MessageBox).</summary>
    Public Property ExecutionResult As NpcOverrideSaver.SaveExecutionResult = Nothing

    ''' <summary>True while the save orchestrator is running. Used by OnFormClosing to block
    ''' user-initiated closes mid-write. Inferring this from PanelProgress.Visible was unreliable
    ''' because the panel stays visible on the success path until Close() runs, and an earlier
    ''' cancelled X-click could leave CloseReason sticky as UserClosing.</summary>
    Private _workInProgress As Boolean = False

    ''' <summary>Total number of high-level steps for the current save run. Computed at the
    ''' start of OnOkClick from the SaveTarget (depends on update-vs-new and CharGen yes/no).
    ''' Drives the determinate ProgressBarMain so the user sees real progress instead of a
    ''' marquee.</summary>
    Private _totalSteps As Integer = 0
    Private _currentStep As Integer = 0
    ''' <summary>Ordered list of Phase-substring → step-number mappings. The orchestrator emits
    ''' free-form Phase strings; we match by substring (stable across minor wording changes)
    ''' to advance the counter. Built in OnOkClick once per run.</summary>
    Private _stepMap As List(Of (Match As String, StepNumber As Integer)) = Nothing

    Public Sub New(dataPath As String,
                   existingPlugins As List(Of ExistingPlugin),
                   targetNpcFormID As UInteger,
                   sourceMasterIsEsm As Boolean,
                   npcIsCharGenFacePreset As Boolean,
                   saveNpc As NPC_Data,
                   saveRawRecord As PluginRecord,
                   saveRawNpcSpec As NPC_Data,
                   saveSourcePluginName As String,
                   saveBaseStateValid As Boolean,
                   saveBaseStateWeightThin As Single,
                   saveBaseStateWeightMuscular As Single,
                   saveBaseStateWeightFat As Single,
                   saveCtx As NpcOverrideSaver.SaveContext)
        InitializeComponent()
        _dataPath = dataPath
        _existingPlugins = If(existingPlugins, New List(Of ExistingPlugin)())
        _targetNpcFormID = targetNpcFormID
        _sourceMasterIsEsm = sourceMasterIsEsm
        _npcIsCharGenFacePreset = npcIsCharGenFacePreset
        _saveNpc = saveNpc
        _saveRawRecord = saveRawRecord
        _saveRawNpcSpec = saveRawNpcSpec
        _saveSourcePluginName = saveSourcePluginName
        _saveBaseStateValid = saveBaseStateValid
        _saveBaseStateWeightThin = saveBaseStateWeightThin
        _saveBaseStateWeightMuscular = saveBaseStateWeightMuscular
        _saveBaseStateWeightFat = saveBaseStateWeightFat
        _saveCtx = saveCtx

        ' CharGen checkbox: default ON in both cases. When the NPC has no CharGen Face Preset
        ' flag, the engine relies on CK's baked FaceGen — without our BA2 the NPC renders as
        ' a generic head — so the checkbox is forced True and disabled. When the flag IS set,
        ' the engine reconstructs at runtime from records, so the bake is optional and the
        ' user can turn it off (still defaults ON for parity).
        CheckBoxGenerateChargen.Checked = True
        If Not _npcIsCharGenFacePreset Then
            CheckBoxGenerateChargen.Enabled = False
            CheckBoxGenerateChargen.Text = CheckBoxGenerateChargen.Text &
                "  (required — NPC has no CharGen Preset flag)"
        End If

        PopulateExistingList()
        ' Default to "create new" when no existing plugins, else "update existing".
        If _existingPlugins.Count > 0 Then
            RadioButtonExisting.Checked = True
            RadioButtonNew.Checked = False
        Else
            RadioButtonExisting.Enabled = False
            RadioButtonExisting.Text = RadioButtonExisting.Text & "  (none found)"
            RadioButtonNew.Checked = True
        End If

        ' Defaults for "Create new": no master flag, light flag on. ApplyFlagDefaultsForCreateNew
        ' is also the reset hook when the user toggles back from "Update existing" to "Create new".
        ApplyFlagDefaultsForCreateNew()

        AddHandler RadioButtonExisting.CheckedChanged, AddressOf OnRadioChanged
        AddHandler RadioButtonNew.CheckedChanged, AddressOf OnRadioChanged
        AddHandler ListBoxExisting.SelectedIndexChanged, AddressOf OnSelectionChanged
        AddHandler TextBoxNewName.TextChanged, AddressOf OnSelectionChanged
        AddHandler ButtonOk.Click, AddressOf OnOkClick

        PopulateEncodingCombo()
        InitBa2VersionCombo()

        OnRadioChanged(Nothing, EventArgs.Empty)
        UpdateWarning()
    End Sub

    ''' <summary>FO4-only BA2 header version selector. Hidden for SSE (which packs BSA v105 — no
    ''' version choice). Index 0 = v8 (Next Gen, default); index 1 = v1 (Old Gen / universal).
    ''' Persists into NPC_Config.Ba2Version_FO4, read at pack time by RunChargenBakeAndPack.</summary>
    Private Sub InitBa2VersionCombo()
        ComboBoxBa2Version.Items.Clear()
        ComboBoxBa2Version.Items.Add("8 - Next Gen (NG)")
        ComboBoxBa2Version.Items.Add("1 - Old Gen (OG / universal)")
        ' Set selection BEFORE wiring the handler so this init does not write config back.
        ComboBoxBa2Version.SelectedIndex = If(NPC_Config.Current.Ba2Version_FO4 = 1UI, 1, 0)
        AddHandler ComboBoxBa2Version.SelectedIndexChanged, AddressOf OnBa2VersionChanged

        Dim isFo4 As Boolean = (Config_App.Current.Game = Config_App.Game_Enum.Fallout4)
        LabelBa2Version.Visible = isFo4
        ComboBoxBa2Version.Visible = isFo4
    End Sub

    Private Sub OnBa2VersionChanged(sender As Object, e As EventArgs)
        ' Index 0 = v8 (Next Gen, default); index 1 = v1 (Old Gen / universal).
        NPC_Config.Current.Ba2Version_FO4 = If(ComboBoxBa2Version.SelectedIndex = 1, 1UI, 8UI)
    End Sub

    ''' <summary>Encoding selector entries. Mirror of xEdit -cp-trans command-line param values
    ''' (xeInit.pas:1320) plus the per-language Auto option (mirror of xeInit.pas:1297 sLanguage
    ''' lookup). Default UTF-8 matches xeInit.pas:1122 wbLEncodingDefault[False] for FO4.</summary>
    Private NotInheritable Class EncodingOption
        Public Property Label As String
        ''' <summary>Code page string passed to PluginEncodingSettings.SetTranslatableOverride.
        ''' Empty means "use Auto sLanguage" (no override; whatever startup set stays in force).</summary>
        Public Property OverrideValue As String
        Public Overrides Function ToString() As String
            Return Label
        End Function
    End Class

    Private Sub PopulateEncodingCombo()
        ComboBoxEncoding.Items.Clear()

        Dim utf8 As New EncodingOption With {.Label = "UTF-8 (recommended — FO4 default)", .OverrideValue = "65001"}
        ComboBoxEncoding.Items.Add(utf8)
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Auto (sLanguage from Fallout4.ini)", .OverrideValue = ""})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1252 (Western European)", .OverrideValue = "1252"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1250 (Central European)", .OverrideValue = "1250"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1251 (Cyrillic / Russian)", .OverrideValue = "1251"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1253 (Greek)", .OverrideValue = "1253"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1254 (Turkish)", .OverrideValue = "1254"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "Windows-1256 (Arabic)", .OverrideValue = "1256"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "CP932 (Japanese Shift-JIS)", .OverrideValue = "932"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "CP936 (Simplified Chinese GBK)", .OverrideValue = "936"})
        ComboBoxEncoding.Items.Add(New EncodingOption With {.Label = "CP950 (Traditional Chinese Big5)", .OverrideValue = "950"})

        ComboBoxEncoding.SelectedItem = utf8
    End Sub

    ''' <summary>Resolve the user's choice into the value passed to SetTranslatableOverride.
    ''' Empty means "leave the startup-applied Auto setting in place".</summary>
    Private Function GetSelectedEncodingOverride() As String
        Dim opt = TryCast(ComboBoxEncoding.SelectedItem, EncodingOption)
        If opt Is Nothing Then Return "65001"   ' fall back to UTF-8 if something went sideways
        Return opt.OverrideValue
    End Function


    ''' <summary>Reset the Master / Light checkboxes to the "Create new" defaults: plain ESP
    ''' (no master flag) with the Light flag on. Called at form construction and whenever the
    ''' user switches back from "Update existing" to "Create new".</summary>
    Private Sub ApplyFlagDefaultsForCreateNew()
        CheckBoxMarkAsMaster.Checked = False
        CheckBoxLightMaster.Checked = True
        ' "Create new" returns the encoding combo to the UTF-8 default (FO4 default per
        ' xeInit.pas:1122). User can still pick a different value before saving.
        SelectEncodingComboByCodePage(65001)
    End Sub

    ''' <summary>Sync the Master / Light checkboxes to whatever the selected existing plugin
    ''' actually has on disk. Called whenever the user picks a different plugin from the list,
    ''' so the saved file keeps the same flag set unless the user explicitly changes them.</summary>
    Private Sub ApplyFlagsFromExisting(ep As ExistingPlugin)
        If ep Is Nothing Then Return
        CheckBoxMarkAsMaster.Checked = ep.IsEsm
        CheckBoxLightMaster.Checked = ep.IsLight
        ' Auto-select the encoding combo to match the plugin's per-file <cp:XXXX> tag so the
        ' rewrite preserves it. Nothing on the ep means the plugin had no tag → default UTF-8
        ' (FO4 canonical default). User can override before clicking Save.
        Dim cp = If(ep.TranslatableEncoding IsNot Nothing, ep.TranslatableEncoding.CodePage, 65001)
        SelectEncodingComboByCodePage(cp)
    End Sub

    ''' <summary>Find the encoding combo item whose OverrideValue maps to the given code page
    ''' and select it. No-op if no match (e.g. an exotic code page we don't expose).</summary>
    Private Sub SelectEncodingComboByCodePage(codePage As Integer)
        If ComboBoxEncoding Is Nothing OrElse ComboBoxEncoding.Items.Count = 0 Then Return
        Dim target = codePage.ToString()
        For Each item In ComboBoxEncoding.Items
            Dim opt = TryCast(item, EncodingOption)
            If opt Is Nothing Then Continue For
            If opt.OverrideValue = target Then
                ComboBoxEncoding.SelectedItem = opt
                Return
            End If
        Next
    End Sub

    Private Sub PopulateExistingList()
        ListBoxExisting.BeginUpdate()
        ListBoxExisting.Items.Clear()
        For Each ep In _existingPlugins
            ListBoxExisting.Items.Add(ep)
        Next
        If ListBoxExisting.Items.Count > 0 Then ListBoxExisting.SelectedIndex = 0
        ListBoxExisting.EndUpdate()
    End Sub

    Private Sub OnRadioChanged(sender As Object, e As EventArgs)
        Dim isExisting = RadioButtonExisting.Checked
        ListBoxExisting.Enabled = isExisting AndAlso _existingPlugins.Count > 0
        TextBoxNewName.Enabled = Not isExisting
        ' Sync the flag checkboxes: when entering "Update existing" mirror the currently-selected
        ' plugin's on-disk flags, when entering "Create new" reset to the new-plugin defaults.
        If isExisting Then
            ApplyFlagsFromExisting(TryCast(ListBoxExisting.SelectedItem, ExistingPlugin))
        Else
            ApplyFlagDefaultsForCreateNew()
        End If
        UpdateEncodingHint()
        UpdateWarning()
    End Sub

    ''' <summary>
    ''' Make it visible in the UI that the encoding combo is auto-detected (preserved) from the
    ''' selected plugin in "Update existing" mode, vs a free choice in "Create new" mode. Without
    ''' this, the combo silently switches to e.g. "Windows-1251" and the user can't tell whether
    ''' that's their choice or came from the plugin.
    ''' </summary>
    Private Sub UpdateEncodingHint()
        If RadioButtonExisting.Checked Then
            LabelEncodingHint.Text = "(from plugin)"
        Else
            LabelEncodingHint.Text = ""
        End If
    End Sub

    Private Sub OnSelectionChanged(sender As Object, e As EventArgs)
        ' Re-sync flags when the user picks a different existing plugin. The text-box change
        ' on the "Create new" side hits this handler too but ApplyFlagsFromExisting bails on
        ' Nothing, so it's a no-op there.
        If RadioButtonExisting.Checked Then
            ApplyFlagsFromExisting(TryCast(ListBoxExisting.SelectedItem, ExistingPlugin))
        End If
        UpdateWarning()
    End Sub

    Private Sub UpdateWarning()
        If RadioButtonExisting.Checked Then
            Dim sel As ExistingPlugin = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
            If sel IsNot Nothing AndAlso sel.ContainsTargetNpc Then
                LabelWarning.Text = "Warning: this plugin already overrides the selected NPC. " &
                                    "The existing override will be replaced with the current state."
                Return
            End If
        End If
        ' Detect collision: target NPC already overridden in some OTHER auto-gen plugin.
        Dim collidingPlugins = _existingPlugins.
            Where(Function(p) p.ContainsTargetNpc).
            Select(Function(p) p.FileName).
            ToList()
        If collidingPlugins.Count > 0 Then
            LabelWarning.Text = "Warning: this NPC is already overridden in: " &
                                String.Join(", ", collidingPlugins) &
                                ". Last-loaded plugin wins; consider updating the existing one instead."
            Return
        End If
        LabelWarning.Text = ""
    End Sub

    ''' <summary>Validates the user's input, builds a <see cref="SaveTarget"/>. Returns Nothing
    ''' on validation failure (the user has been notified via MessageBox).</summary>
    Private Function BuildTargetFromUi() As SaveTarget
        Dim target As New SaveTarget With {
            .MarkAsMaster = CheckBoxMarkAsMaster.Checked,
            .LightMaster = CheckBoxLightMaster.Checked,
            .GenerateChargen = CheckBoxGenerateChargen.Checked,
            .WriteBssliders = CheckBoxWriteBssliders.Checked,
            .EmitBodyGen = CheckBoxEmitBodyGen.Checked
        }

        If RadioButtonExisting.Checked Then
            Dim sel As ExistingPlugin = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
            If sel Is Nothing Then
                MessageBox.Show(Me, "Select an existing plugin or switch to 'Create new'.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                Return Nothing
            End If
            target.TargetPath = sel.FullPath
            target.IsNewPlugin = False
            target.ReplacingExistingNpc = sel.ContainsTargetNpc
        Else
            Dim baseName = TextBoxNewName.Text.Trim()
            If String.IsNullOrWhiteSpace(baseName) Then
                MessageBox.Show(Me, "Plugin name cannot be empty.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                Return Nothing
            End If
            If baseName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0 Then
                MessageBox.Show(Me, "Plugin name contains invalid characters.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                Return Nothing
            End If
            If baseName.EndsWith(".esp", StringComparison.OrdinalIgnoreCase) OrElse
               baseName.EndsWith(".esm", StringComparison.OrdinalIgnoreCase) OrElse
               baseName.EndsWith(".esl", StringComparison.OrdinalIgnoreCase) Then
                baseName = Path.GetFileNameWithoutExtension(baseName)
            End If
            Dim candidate = baseName & ".esp"
            Dim suffix = 2
            While File.Exists(Path.Combine(_dataPath, candidate))
                candidate = $"{baseName}_{suffix}.esp"
                suffix += 1
            End While
            target.TargetPath = Path.Combine(_dataPath, candidate)
            target.IsNewPlugin = True
            target.ReplacingExistingNpc = False
        End If

        Return target
    End Function

    ''' <summary>Async OK handler. Validates, then runs the save orchestrator while showing
    ''' progress in the embedded panel. Closes with DialogResult.OK on success, leaves the
    ''' form open and re-enables controls on failure so the user can retry. Cancel is
    ''' disabled during execution; <see cref="OnFormClosing"/> blocks closes while the work
    ''' is running so the user can't tear the dialog down mid-write.</summary>
    Private Async Sub OnOkClick(sender As Object, e As EventArgs)
        Dim target = BuildTargetFromUi()
        If target Is Nothing Then Return
        Result = target

        ' Apply translatable-encoding override BEFORE BuildStepPlan / ExecuteAsync. The writer
        ' reads PluginEncodingSettings.Translatable inside EmitLString — once the write starts
        ' it's too late to change. Empty value means "Auto" (leave whatever MainForm_Load set
        ' from Fallout4.ini sLanguage in place). Mirror of xEdit -cp-trans command-line param.
        Dim encOverride = GetSelectedEncodingOverride()
        If encOverride <> "" Then PluginEncodingSettings.SetTranslatableOverride(encOverride)
        ' NOTE: encoding-conflict pre-check (FULL/SHRT/ATTX vs selected encoding, for the edited
        ' NPC + all pre-existing NPCs when updating) runs inside NpcOverrideSaver.ExecuteWritePhases
        ' right after the existing plugin is loaded — reusing that single PluginReader.Load instead
        ' of loading the plugin twice. A conflict aborts the save with a descriptive message.

        ' Lock UI: every interactive control (except the form chrome) goes disabled and the
        ' progress panel becomes visible. Cancel button stays disabled too — the orchestrator
        ' has no cancellation token plumbed through (writer + bake + BA2 pack run synchronously
        ' on the worker Task), so offering a Cancel that doesn't actually cancel would lie.
        _workInProgress = True
        BuildStepPlan(target)
        LockUiForExecution(True)

        Dim progress As New Progress(Of NpcOverrideSaver.SaveProgress)(AddressOf ApplyProgress)

        Try
            ExecutionResult = Await NpcOverrideSaver.ExecuteAsync(
                target,
                _targetNpcFormID,
                _saveNpc,
                _saveRawRecord,
                _saveRawNpcSpec,
                _saveSourcePluginName,
                _saveBaseStateWeightThin,
                _saveBaseStateWeightMuscular,
                _saveBaseStateWeightFat,
                _saveBaseStateValid,
                _saveCtx,
                progress)
        Catch ex As Exception
            ' ExecuteAsync wraps internal failures in ExecutionResult.ErrorMessage; this Catch
            ' only fires for genuinely unexpected failures (e.g. orchestrator constructor crash).
            ExecutionResult = New NpcOverrideSaver.SaveExecutionResult With {
                .Success = False,
                .ErrorMessage = ex.Message
            }
        End Try

        ' Clear the in-progress flag BEFORE Close() so OnFormClosing's guard does not block
        ' the programmatic close. The guard only fires while work is actually running; once
        ' the awaited orchestrator returns there is nothing to protect.
        _workInProgress = False

        If ExecutionResult IsNot Nothing AndAlso ExecutionResult.Success Then
            DialogResult = DialogResult.OK
            Close()
        Else
            ' Failure: re-enable UI so the user can adjust and retry, surface the error inline.
            LockUiForExecution(False)
            Dim msg = "Save failed."
            If ExecutionResult IsNot Nothing AndAlso Not String.IsNullOrEmpty(ExecutionResult.ErrorMessage) Then
                msg = "Save failed: " & ExecutionResult.ErrorMessage
            End If
            MessageBox.Show(Me, msg, "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Error)
        End If
    End Sub

    ''' <summary>Toggle interactive controls + progress panel visibility for the work phase.
    ''' True = lock (work running), False = restore (user can retry).</summary>
    Private Sub LockUiForExecution(locked As Boolean)
        Dim enabled = Not locked
        RadioButtonExisting.Enabled = enabled AndAlso _existingPlugins.Count > 0
        RadioButtonNew.Enabled = enabled
        ListBoxExisting.Enabled = enabled AndAlso RadioButtonExisting.Checked AndAlso _existingPlugins.Count > 0
        TextBoxNewName.Enabled = enabled AndAlso RadioButtonNew.Checked
        CheckBoxMarkAsMaster.Enabled = enabled
        CheckBoxLightMaster.Enabled = enabled
        ' Chargen checkbox stays disabled when forced-True for non-CharGenPreset NPCs (its
        ' constructor-time disabled state is sticky); only re-enable here when the NPC allows opt-out.
        CheckBoxGenerateChargen.Enabled = enabled AndAlso _npcIsCharGenFacePreset
        CheckBoxWriteBssliders.Enabled = enabled
        CheckBoxEmitBodyGen.Enabled = enabled
        ComboBoxEncoding.Enabled = enabled
        ComboBoxBa2Version.Enabled = enabled
        ButtonOk.Enabled = enabled
        ButtonCancel.Enabled = enabled
        PanelProgress.Visible = locked
        If locked Then
            ' Determinate from step 0; ApplyProgress advances as Phase strings arrive.
            ProgressBarMain.Style = ProgressBarStyle.Continuous
            ProgressBarMain.Minimum = 0
            ProgressBarMain.Maximum = Math.Max(1, _totalSteps)
            ProgressBarMain.Value = 0
        Else
            ProgressBarMain.Style = ProgressBarStyle.Continuous
            ProgressBarMain.Value = ProgressBarMain.Minimum
            LabelProgressStage.Text = ""
            LabelProgressDetail.Text = ""
        End If
    End Sub

    ''' <summary>Build the Phase→step map for the current SaveTarget. Phases are matched by
    ''' substring because the orchestrator's free-form strings include trailing ellipses and
    ''' contextual detail. Steps depend on:
    '''   - update-existing (adds "Loading existing plugin…") vs new plugin (skips it)
    '''   - GenerateChargen on (adds 4 bake/pack steps) vs off
    ''' Total ranges from 4 (new plugin, no chargen) to 9 (update existing + chargen).</summary>
    Private Sub BuildStepPlan(target As SaveTarget)
        Dim map As New List(Of (Match As String, StepNumber As Integer))
        Dim n As Integer = 0
        n += 1 : map.Add(("Preparing NPC record", n))
        If Not target.IsNewPlugin Then
            n += 1 : map.Add(("Loading existing plugin", n))
        End If
        n += 1 : map.Add(("Writing NPC override", n))
        n += 1 : map.Add(("Verifying written record", n))
        If target.WriteBssliders Then
            n += 1 : map.Add(("Writing .bssliders sidecar", n))
        End If
        If target.EmitBodyGen Then
            n += 1 : map.Add(("Writing BodyGen", n))
        End If
        If target.GenerateChargen Then
            n += 1 : map.Add(("Baking CharGen", n))
            n += 1 : map.Add(("Compressing FaceGen bundle", n))
            n += 1 : map.Add(("Writing BA2", n))
            n += 1 : map.Add(("Removing loose files", n))
        End If
        ' "Done." is reported by the packer on the chargen path; on the no-chargen path the
        ' orchestrator just returns. Either way we want the final tick when work completes,
        ' so we map "Done" to (n+1) and bump the total to include it.
        n += 1 : map.Add(("Done", n))
        _stepMap = map
        _totalSteps = n
        _currentStep = 0
    End Sub

    ''' <summary>Resolve the step number for a Phase string by first-substring match against
    ''' the plan. Returns 0 if no entry matches (orchestrator may emit detail-only updates we
    ''' don't want to advance on — e.g. "Removed 3/8" sub-progress reuses the parent phase).</summary>
    Private Function ResolveStep(phase As String) As Integer
        If _stepMap Is Nothing OrElse String.IsNullOrEmpty(phase) Then Return 0
        For Each entry In _stepMap
            If phase.IndexOf(entry.Match, StringComparison.OrdinalIgnoreCase) >= 0 Then
                Return entry.StepNumber
            End If
        Next
        Return 0
    End Function

    ''' <summary>IProgress(Of T) callback. Marshaled to the UI thread by the runtime, so it can
    ''' touch controls directly. Maps the orchestrator's free-form Phase to a step number and
    ''' advances the determinate ProgressBarMain. Sub-phase progress (compress N/4, remove N/M)
    ''' surfaces in the detail label only — the main bar tracks high-level steps so the user
    ''' always sees "Step k/N: …".</summary>
    Private Sub ApplyProgress(p As NpcOverrideSaver.SaveProgress)
        If p Is Nothing Then Return
        Dim phase = If(p.Phase, "")
        Dim resolved = ResolveStep(phase)
        If resolved > 0 Then
            ' Steps only move forward — guards against out-of-order reports (shouldn't happen
            ' but the orchestrator emits sub-progress under reused phase strings).
            If resolved > _currentStep Then _currentStep = resolved
        End If

        Dim shownStep As Integer = Math.Max(_currentStep, 1)
        LabelProgressStage.Text = $"Step {shownStep}/{_totalSteps}: {phase}"
        LabelProgressDetail.Text = If(p.Detail, "")

        ProgressBarMain.Maximum = Math.Max(1, _totalSteps)
        ProgressBarMain.Value = Math.Max(0, Math.Min(_currentStep, ProgressBarMain.Maximum))
    End Sub

    ''' <summary>Block close attempts while the save is running. The form has no Cancel-the-work
    ''' path, so allowing close mid-write would orphan the worker Task and risk a half-written
    ''' plugin file. Driven by the explicit <see cref="_workInProgress"/> flag rather than
    ''' PanelProgress.Visible — the panel stays visible on the success path until Close() runs,
    ''' and CloseReason can be sticky as UserClosing if a prior X-click was cancelled.</summary>
    Protected Overrides Sub OnFormClosing(e As FormClosingEventArgs)
        If _workInProgress AndAlso e.CloseReason = CloseReason.UserClosing Then
            e.Cancel = True
            Return
        End If
        MyBase.OnFormClosing(e)
    End Sub

End Class
