Imports System.IO
Imports FO4_Base_Library

''' <summary>
''' Dialog for "Save ESP/ESM" — picks a target plugin (existing auto-generated or new)
''' and the light-master flag. Scans the Data\ folder for plugins whose TES4.CNAM matches
''' the NPC_Manager canonical author string and lists them as "update existing" candidates.
''' </summary>
Public Class SaveEsp_Form

    ' ============================================================================
    ' Shared scan helpers (used by both Preflight_Form to populate the cache up-front
    ' during the splash, and by MainForm to re-scan if needed).
    ' ============================================================================

    ''' <summary>Full disk scan for NPC_Manager auto-generated plugins. Walks Data\, filters by
    ''' TES4.CNAM matching <see cref="PluginWriter.NPC_MANAGER_AUTHOR_CNAM"/>, then loads each
    ''' match to enumerate its NPC overrides. Best-effort: malformed plugins are skipped silently.
    '''
    ''' Designed to run during Preflight (splash screen) so the first Save ESP dialog opens
    ''' instantly. Reports progress via the optional <paramref name="progress"/> callback.</summary>
    Public Shared Function ScanAutoGeneratedPlugins(dataPath As String, Optional progress As IProgress(Of String) = Nothing) As List(Of ExistingPlugin)
        Dim result As New List(Of ExistingPlugin)
        If String.IsNullOrEmpty(dataPath) OrElse Not Directory.Exists(dataPath) Then Return result

        Dim pluginFiles = Directory.GetFiles(dataPath, "*.esp").
            Concat(Directory.GetFiles(dataPath, "*.esm")).
            Concat(Directory.GetFiles(dataPath, "*.esl")).
            ToList()

        Dim total = pluginFiles.Count
        Dim idx As Integer = 0
        For Each filePath In pluginFiles
            idx += 1
            Try
                Dim author = TryReadTes4Author(filePath)
                If author Is Nothing OrElse Not String.Equals(author, PluginWriter.NPC_MANAGER_AUTHOR_CNAM, StringComparison.Ordinal) Then
                    Continue For
                End If

                progress?.Report($"Scanning auto-generated plugins ({idx}/{total}): {Path.GetFileName(filePath)}")

                Dim reader As New PluginReader()
                reader.Load(filePath)
                Dim npcIds As New HashSet(Of UInteger)
                For Each kvp In reader.Records
                    If kvp.Value.Header.Signature = "NPC_" Then npcIds.Add(kvp.Key)
                Next
                Dim ep As New ExistingPlugin With {
                    .FullPath = filePath,
                    .FileName = Path.GetFileName(filePath),
                    .NpcCount = npcIds.Count,
                    .NpcFormIDs = npcIds,
                    .ContainsTargetNpc = False
                }
                result.Add(ep)
            Catch
                ' Plugin failed to read or open — skip silently.
            End Try
        Next
        Return result
    End Function

    ''' <summary>Read just the TES4 CNAM (author string) from a plugin file. Returns Nothing
    ''' if the plugin is malformed or has no author. Cheap: only reads the TES4 record body
    ''' (typically &lt; 1 KB) so the scan can dismiss most plugins without loading them.</summary>
    Public Shared Function TryReadTes4Author(path As String) As String
        Try
            Using fs As New FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read)
                Using br As New BinaryReader(fs)
                    ' TES4 record header layout (24 bytes total):
                    '   +0  sig "TES4" (4)
                    '   +4  DataSize u32 (4)
                    '   +8  Flags u32 (4)
                    '   +12 FormID u32 (4)
                    '   +16 VCS1 u32 (4)
                    '   +20 Version u16 (2)
                    '   +22 VCS2 u16 (2)
                    ' After reading sig+DataSize (8 bytes consumed), skip 16 more to land at body.
                    Dim sig = System.Text.Encoding.ASCII.GetString(br.ReadBytes(4))
                    If sig <> "TES4" Then Return Nothing
                    Dim dataSize = br.ReadUInt32()
                    fs.Seek(16, SeekOrigin.Current)
                    Dim bodyEnd = fs.Position + CLng(dataSize)
                    While fs.Position <= bodyEnd - 6
                        Dim subSig = System.Text.Encoding.ASCII.GetString(br.ReadBytes(4))
                        Dim subSize = br.ReadUInt16()
                        If subSig = "CNAM" Then
                            Dim bytes = br.ReadBytes(CInt(subSize))
                            ' Strip NUL terminator.
                            Dim len = bytes.Length
                            If len > 0 AndAlso bytes(len - 1) = 0 Then len -= 1
                            Return System.Text.Encoding.ASCII.GetString(bytes, 0, len)
                        End If
                        fs.Seek(CLng(subSize), SeekOrigin.Current)
                    End While
                End Using
            End Using
        Catch
            Return Nothing
        End Try
        Return Nothing
    End Function

    ''' <summary>An auto-generated plugin found on disk that the user can update.</summary>
    Public Class ExistingPlugin
        Public FileName As String
        Public FullPath As String
        Public NpcCount As Integer
        ''' <summary>FormIDs of the NPC_ overrides this plugin contains. Captured at scan time
        ''' so the cache can answer ContainsTargetNpc for any target NPC without re-reading
        ''' the plugin from disk.</summary>
        Public NpcFormIDs As HashSet(Of UInteger)
        Public ContainsTargetNpc As Boolean

        Public Overrides Function ToString() As String
            Dim suffix As String = ""
            If ContainsTargetNpc Then
                suffix = "  (already contains this NPC — will be replaced)"
            ElseIf NpcCount > 0 Then
                suffix = $"  ({NpcCount} NPC override{If(NpcCount = 1, "", "s")})"
            End If
            Return $"{FileName}{suffix}"
        End Function
    End Class

    ''' <summary>Result of the dialog when the user clicks Save.</summary>
    Public Class SaveTarget
        Public TargetPath As String
        Public IsNewPlugin As Boolean
        Public LightMaster As Boolean
        Public ReplacingExistingNpc As Boolean
    End Class

    Private ReadOnly _dataPath As String
    Private ReadOnly _existingPlugins As List(Of ExistingPlugin)
    Private ReadOnly _targetNpcFormID As UInteger
    Private ReadOnly _sourceMasterIsEsm As Boolean

    Public Property Result As SaveTarget = Nothing

    Public Sub New(dataPath As String,
                   existingPlugins As List(Of ExistingPlugin),
                   targetNpcFormID As UInteger,
                   sourceMasterIsEsm As Boolean)
        InitializeComponent()
        _dataPath = dataPath
        _existingPlugins = If(existingPlugins, New List(Of ExistingPlugin)())
        _targetNpcFormID = targetNpcFormID
        _sourceMasterIsEsm = sourceMasterIsEsm

        PopulateExistingList()
        ' Default to "create new" when no existing plugins, else "update existing".
        If _existingPlugins.Count > 0 Then
            RadioButtonExisting.Checked = True
            RadioButtonNew.Checked = False
        Else
            RadioButtonExisting.Enabled = False
            RadioButtonExisting.Text = RadioButtonExisting.Text & "  (none found)"
            RadioButtonNew.Checked = True
        End If

        ' Light master default mirrors the source NPC's master plugin: if the NPC originally
        ' lives in an ESM, light master is safe (most common case). Otherwise default to off
        ' (full ESP) but let the user override.
        CheckBoxLightMaster.Checked = _sourceMasterIsEsm

        AddHandler RadioButtonExisting.CheckedChanged, AddressOf OnRadioChanged
        AddHandler RadioButtonNew.CheckedChanged, AddressOf OnRadioChanged
        AddHandler ListBoxExisting.SelectedIndexChanged, AddressOf OnSelectionChanged
        AddHandler TextBoxNewName.TextChanged, AddressOf OnSelectionChanged
        AddHandler ButtonOk.Click, AddressOf OnOkClick

        OnRadioChanged(Nothing, EventArgs.Empty)
        UpdateWarning()
    End Sub

    Private Sub PopulateExistingList()
        ListBoxExisting.BeginUpdate()
        ListBoxExisting.Items.Clear()
        For Each ep In _existingPlugins
            ListBoxExisting.Items.Add(ep)
        Next
        If ListBoxExisting.Items.Count > 0 Then ListBoxExisting.SelectedIndex = 0
        ListBoxExisting.EndUpdate()
    End Sub

    Private Sub OnRadioChanged(sender As Object, e As EventArgs)
        Dim isExisting = RadioButtonExisting.Checked
        ListBoxExisting.Enabled = isExisting AndAlso _existingPlugins.Count > 0
        TextBoxNewName.Enabled = Not isExisting
        UpdateWarning()
    End Sub

    Private Sub OnSelectionChanged(sender As Object, e As EventArgs)
        UpdateWarning()
    End Sub

    Private Sub UpdateWarning()
        If RadioButtonExisting.Checked Then
            Dim sel As ExistingPlugin = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
            If sel IsNot Nothing AndAlso sel.ContainsTargetNpc Then
                LabelWarning.Text = "Warning: this plugin already overrides the selected NPC. " &
                                    "The existing override will be replaced with the current state."
                Return
            End If
        End If
        ' Detect collision: target NPC already overridden in some OTHER auto-gen plugin.
        Dim collidingPlugins = _existingPlugins.
            Where(Function(p) p.ContainsTargetNpc).
            Select(Function(p) p.FileName).
            ToList()
        If collidingPlugins.Count > 0 Then
            LabelWarning.Text = "Warning: this NPC is already overridden in: " &
                                String.Join(", ", collidingPlugins) &
                                ". Last-loaded plugin wins; consider updating the existing one instead."
            Return
        End If
        LabelWarning.Text = ""
    End Sub

    Private Sub OnOkClick(sender As Object, e As EventArgs)
        Dim target As New SaveTarget With {.LightMaster = CheckBoxLightMaster.Checked}

        If RadioButtonExisting.Checked Then
            Dim sel As ExistingPlugin = TryCast(ListBoxExisting.SelectedItem, ExistingPlugin)
            If sel Is Nothing Then
                MessageBox.Show(Me, "Select an existing plugin or switch to 'Create new'.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                DialogResult = DialogResult.None
                Return
            End If
            target.TargetPath = sel.FullPath
            target.IsNewPlugin = False
            target.ReplacingExistingNpc = sel.ContainsTargetNpc
        Else
            Dim baseName = TextBoxNewName.Text.Trim()
            If String.IsNullOrWhiteSpace(baseName) Then
                MessageBox.Show(Me, "Plugin name cannot be empty.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                DialogResult = DialogResult.None
                Return
            End If
            ' Sanitize: no path separators, no extension on input.
            If baseName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0 Then
                MessageBox.Show(Me, "Plugin name contains invalid characters.",
                                "Save ESP/ESM", MessageBoxButtons.OK, MessageBoxIcon.Warning)
                DialogResult = DialogResult.None
                Return
            End If
            If baseName.EndsWith(".esp", StringComparison.OrdinalIgnoreCase) OrElse
               baseName.EndsWith(".esm", StringComparison.OrdinalIgnoreCase) OrElse
               baseName.EndsWith(".esl", StringComparison.OrdinalIgnoreCase) Then
                baseName = Path.GetFileNameWithoutExtension(baseName)
            End If
            ' Auto-suffix on collision: NPC_Manager.esp, NPC_Manager_2.esp, ...
            Dim candidate = baseName & ".esp"
            Dim suffix = 2
            While File.Exists(Path.Combine(_dataPath, candidate))
                candidate = $"{baseName}_{suffix}.esp"
                suffix += 1
            End While
            target.TargetPath = Path.Combine(_dataPath, candidate)
            target.IsNewPlugin = True
            target.ReplacingExistingNpc = False
        End If

        Result = target
        DialogResult = DialogResult.OK
    End Sub

End Class
